In [1]:
import json
import pandas as pd
from haversine import haversine
import zipcodes

In [2]:
file_json_centers="/mnt/clients/juba/hqjubaapp02/sharefolder/Docs/Geo_mapping/updated_zip_centers_JL_2019-05-23.json"
file_excel_dma="/mnt/clients/juba/hqjubaapp02/sharefolder/Docs/Geo_mapping/Zips by DMA by County16-17 nielsen.xlsx"

In [3]:
zip_centers=json.load(open(file_json_centers,"r"))
# k: zip_cd, v: [lat,lng]

In [10]:
df_dma=pd.ExcelFile(file_excel_dma)
df_dma.sheet_names

['2016_NSI_DMABYZIP (2)']

In [13]:
df_dma=df_dma.parse("2016_NSI_DMABYZIP (2)",dtype=str,skiprows=1)
df_dma=df_dma.iloc[:,[0,2,6]]
df_dma.columns=['zip_cd','dma','st']

In [14]:
df_dma.head(3)

  zip_cd                  dma  st
0  00501             NEW YORK  NY
1  00544             NEW YORK  NY
2  01001  SPRINGFIELD-HOLYOKE  MA

In [7]:
list(zip_centers.keys())[0]

'11542'

In [8]:
zipcodes.matching("11542")

[{'zip_code': '11542',
  'zip_code_type': 'STANDARD',
  'active': True,
  'city': 'Glen Cove',
  'acceptable_cities': [],
  'unacceptable_cities': [],
  'state': 'NY',
  'county': 'Nassau County',
  'timezone': 'America/New_York',
  'area_codes': ['516'],
  'world_region': 'NA',
  'country': 'US',
  'lat': '40.8736',
  'long': '-73.6232'}]

In [15]:
df_zip_all_info=pd.DataFrame()
for z in zip_centers.keys():
    df_from_nielsen=df_dma[df_dma['zip_cd']==z]
    dma=df_from_nielsen['dma'].unique().tolist()
    if len(dma)==0:
        response_list=zipcodes.matching(z)
        st_list=[]
        ct_list=[]
        
        for l in response_list:
            st_list.append(l['state'])
            ct_list.append(l['city'])
        st_list=list(set(st_list))
        ct_list=list(set(ct_list))
    else:
        st_list=df_from_nielsen['st'].unique().tolist()
        response_list=zipcodes.matching(z)
        ct_list=[]
        for l in response_list:
            ct_list.append(l['city'])
        ct_list=list(set(ct_list))
    df=pd.DataFrame({"zip_cd":z,
                     "city_list":str(ct_list),
                     "st_list":str(st_list),
                     "dma_list":str(dma)},index=[0])
    df_zip_all_info=df_zip_all_info.append(df)
df_zip_all_info.head(3)

KeyboardInterrupt:

In [ ]:
# distance between to (lat,lng) pairs
dist=haversine([lat1,lng1],[lat2,lng2],unit="mi")

# Find all zips within 50 miles

In [ ]:
# iterate all zips based on the dist above 

for location in input_l:
    
    for zip_cd in zip_centers.keys():
        dist=.....
        if dist<==x:
            append

In [19]:
# Pop -- zip4
EASI
'''
pro: reliable (purchased zip4)
con: not 50 years old; HH based
'''
df_zip4=pd.read_csv("/mnt/clients/juba/hqjubaapp02/sharefolder/Docs/EASI/2018-07-19/ZIP4_18_DATA_C2_CSV/ZIP4_18_DATA_C2.CSV",
                   dtype=str,nrows=10,skiprows=1)
df_zip4

,ZIP_CODE,ZIP4,CRRTTYPE,HH18,PCTMARNOC,PCTMARC,PCTSPARC,PCTSING,PCTHHL25,PCTHH25_34,PCTHH35_44,PCTHH45_54,PCTHH55_64,PCTHH65_74,PCTHH75P,PCTL35K,PCT35_100K,PCT100KP
0,00501,0001,C,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,00501,0002,C,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,01001,0001,B,45.6,23.79,14.40,10.50,51.31,3.05,19.29,17.34,17.51,21.03,10.38,11.40,27.86,55.71,16.43
3,01001,0121,B,40.9,23.79,14.40,10.50,51.31,3.05,19.29,17.34,17.51,21.03,10.38,11.40,27.86,55.71,16.43
4,01001,0241,B,8.5,23.79,14.40,10.50,51.31,3.05,19.29,17.34,17.51,21.03,10.38,11.40,27.86,55.71,16.43
5,01001,0319,B,12.2,23.79,14.40,10.50,51.31,3.05,19.29,17.34,17.51,21.03,10.38,11.40,27.86,55.71,16.43
6,01001,0401,B,8.9,23.79,14.40,10.50,51.31,3.05,19.29,17.34,17.51,21.03,10.38,11.40,27.86,55.71,16.43
7,01001,0481,B,4.7,23.79,14.40,10.50,51.31,3.05,19.29,17.34,17.51,21.03,10.38,11.40,27.86,55.71,16.43
8,01001,0561,B,23.0,23.79,14.40,10.50,51.31,3.05,19.29,17.34,17.51,21.03,10.38,11.40,27.86,55.71,16.43
9,01001,0661,B,6.6,23.79,14.40,10.50,51.31,3.05,19.29,17.34,17.51,21.03,10.38,11.40,27.86,55.71,16.43

In [21]:
# Pop -- ZCTA cencus
'''
pro: from cencus; population based
con: not zipcode (ZCTA) -- need to match if do precise analysis; zcta to zipcode from online source
'''

df_cencus=pd.read_csv("/mnt/clients/juba/hqjubaapp02/sharefolder/Docs/Household_and_Population/Cencus_2019/ACS_17_5YR_S0101_with_ann.csv",
                     dtype=str,nrows=10,skiprows=1)
l=df_cencus.columns.tolist()
[x for x in l if "error" not in x.lower()]

['Id',
 'Id2',
 'Geography',
 'Total; Estimate; Total population',
 'Percent; Estimate; Total population',
 'Male; Estimate; Total population',
 'Percent Male; Estimate; Total population',
 'Female; Estimate; Total population',
 'Percent Female; Estimate; Total population',
 'Total; Estimate; AGE - Under 5 years',
 'Percent; Estimate; AGE - Under 5 years',
 'Male; Estimate; AGE - Under 5 years',
 'Percent Male; Estimate; AGE - Under 5 years',
 'Female; Estimate; AGE - Under 5 years',
 'Percent Female; Estimate; AGE - Under 5 years',
 'Total; Estimate; AGE - 5 to 9 years',
 'Percent; Estimate; AGE - 5 to 9 years',
 'Male; Estimate; AGE - 5 to 9 years',
 'Percent Male; Estimate; AGE - 5 to 9 years',
 'Female; Estimate; AGE - 5 to 9 years',
 'Percent Female; Estimate; AGE - 5 to 9 years',
 'Total; Estimate; AGE - 10 to 14 years',
 'Percent; Estimate; AGE - 10 to 14 years',
 'Male; Estimate; AGE - 10 to 14 years',
 'Percent Male; Estimate; AGE - 10 to 14 years',
 'Female; Estimate; AGE - 10 to 14 years',
 'Percent Female; Estimate; AGE - 10 to 14 years',
 'Total; Estimate; AGE - 15 to 19 years',
 'Percent; Estimate; AGE - 15 to 19 years',
 'Male; Estimate; AGE - 15 to 19 years',
 'Percent Male; Estimate; AGE - 15 to 19 years',
 'Female; Estimate; AGE - 15 to 19 years',
 'Percent Female; Estimate; AGE - 15 to 19 years',
 'Total; Estimate; AGE - 20 to 24 years',
 'Percent; Estimate; AGE - 20 to 24 years',
 'Male; Estimate; AGE - 20 to 24 years',
 'Percent Male; Estimate; AGE - 20 to 24 years',
 'Female; Estimate; AGE - 20 to 24 years',
 'Percent Female; Estimate; AGE - 20 to 24 years',
 'Total; Estimate; AGE - 25 to 29 years',
 'Percent; Estimate; AGE - 25 to 29 years',
 'Male; Estimate; AGE - 25 to 29 years',
 'Percent Male; Estimate; AGE - 25 to 29 years',
 'Female; Estimate; AGE - 25 to 29 years',
 'Percent Female; Estimate; AGE - 25 to 29 years',
 'Total; Estimate; AGE - 30 to 34 years',
 'Percent; Estimate; AGE - 30 to 34 years',
 'Male; Estimate; AGE - 30 to 34 years',
 'Percent Male; Estimate; AGE - 30 to 34 years',
 'Female; Estimate; AGE - 30 to 34 years',
 'Percent Female; Estimate; AGE - 30 to 34 years',
 'Total; Estimate; AGE - 35 to 39 years',
 'Percent; Estimate; AGE - 35 to 39 years',
 'Male; Estimate; AGE - 35 to 39 years',
 'Percent Male; Estimate; AGE - 35 to 39 years',
 'Female; Estimate; AGE - 35 to 39 years',
 'Percent Female; Estimate; AGE - 35 to 39 years',
 'Total; Estimate; AGE - 40 to 44 years',
 'Percent; Estimate; AGE - 40 to 44 years',
 'Male; Estimate; AGE - 40 to 44 years',
 'Percent Male; Estimate; AGE - 40 to 44 years',
 'Female; Estimate; AGE - 40 to 44 years',
 'Percent Female; Estimate; AGE - 40 to 44 years',
 'Total; Estimate; AGE - 45 to 49 years',
 'Percent; Estimate; AGE - 45 to 49 years',
 'Male; Estimate; AGE - 45 to 49 years',
 'Percent Male; Estimate; AGE - 45 to 49 years',
 'Female; Estimate; AGE - 45 to 49 years',
 'Percent Female; Estimate; AGE - 45 to 49 years',
 'Total; Estimate; AGE - 50 to 54 years',
 'Percent; Estimate; AGE - 50 to 54 years',
 'Male; Estimate; AGE - 50 to 54 years',
 'Percent Male; Estimate; AGE - 50 to 54 years',
 'Female; Estimate; AGE - 50 to 54 years',
 'Percent Female; Estimate; AGE - 50 to 54 years',
 'Total; Estimate; AGE - 55 to 59 years',
 'Percent; Estimate; AGE - 55 to 59 years',
 'Male; Estimate; AGE - 55 to 59 years',
 'Percent Male; Estimate; AGE - 55 to 59 years',
 'Female; Estimate; AGE - 55 to 59 years',
 'Percent Female; Estimate; AGE - 55 to 59 years',
 'Total; Estimate; AGE - 60 to 64 years',
 'Percent; Estimate; AGE - 60 to 64 years',
 'Male; Estimate; AGE - 60 to 64 years',
 'Percent Male; Estimate; AGE - 60 to 64 years',
 'Female; Estimate; AGE - 60 to 64 years',
 'Percent Female; Estimate; AGE - 60 to 64 years',
 'Total; Estimate; AGE - 65 to 69 years',
 'Percent; Estimate; AGE - 65 to 69 years',
 'Male; Estimate; AGE - 65 to 69 years',
 'Percent Male; Estimate; AGE - 65 to 69 years',
 'Female; Estimate; AGE - 65 to 69 years',
 'Percent Female; Estimate; AGE - 65 to 69 years',
 'Total; Estimate; AGE - 70 to 74 years',
 'Percent; Estimate; AGE - 70 to 74 years',
 'Male; Estimate; AGE - 70 to 74 years',
 'Percent Male; Estimate; AGE - 70 to 74 years',
 'Female; Estimate; AGE - 70 to 74 years',
 'Percent Female; Estimate; AGE - 70 to 74 years',
 'Total; Estimate; AGE - 75 to 79 years',
 'Percent; Estimate; AGE - 75 to 79 years',
 'Male; Estimate; AGE - 75 to 79 years',
 'Percent Male; Estimate; AGE - 75 to 79 years',
 'Female; Estimate; AGE - 75 to 79 years',
 'Percent Female; Estimate; AGE - 75 to 79 years',
 'Total; Estimate; AGE - 80 to 84 years',
 'Percent; Estimate; AGE - 80 to 84 years',
 'Male; Estimate; AGE - 80 to 84 years',
 'Percent Male; Estimate; AGE - 80 to 84 years',
 'Female; Estimate; AGE - 80 to 84 years',
 'Percent Female; Estimate; AGE - 80 to 84 years',
 'Total; Estimate; AGE - 85 years and over',
 'Percent; Estimate; AGE - 85 years and over',
 'Male; Estimate; AGE - 85 years and over',
 'Percent Male; Estimate; AGE - 85 years and over',
 'Female; Estimate; AGE - 85 years and over',
 'Percent Female; Estimate; AGE - 85 years and over',
 'Total; Estimate; SELECTED AGE CATEGORIES - 5 to 14 years',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 5 to 14 years',
 'Male; Estimate; SELECTED AGE CATEGORIES - 5 to 14 years',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 5 to 14 years',
 'Female; Estimate; SELECTED AGE CATEGORIES - 5 to 14 years',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 5 to 14 years',
 'Total; Estimate; SELECTED AGE CATEGORIES - 15 to 17 years',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 15 to 17 years',
 'Male; Estimate; SELECTED AGE CATEGORIES - 15 to 17 years',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 15 to 17 years',
 'Female; Estimate; SELECTED AGE CATEGORIES - 15 to 17 years',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 15 to 17 years',
 'Total; Estimate; SELECTED AGE CATEGORIES - Under 18 years',
 'Percent; Estimate; SELECTED AGE CATEGORIES - Under 18 years',
 'Male; Estimate; SELECTED AGE CATEGORIES - Under 18 years',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - Under 18 years',
 'Female; Estimate; SELECTED AGE CATEGORIES - Under 18 years',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - Under 18 years',
 'Total; Estimate; SELECTED AGE CATEGORIES - 18 to 24 years',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 18 to 24 years',
 'Male; Estimate; SELECTED AGE CATEGORIES - 18 to 24 years',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 18 to 24 years',
 'Female; Estimate; SELECTED AGE CATEGORIES - 18 to 24 years',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 18 to 24 years',
 'Total; Estimate; SELECTED AGE CATEGORIES - 15 to 44 years',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 15 to 44 years',
 'Male; Estimate; SELECTED AGE CATEGORIES - 15 to 44 years',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 15 to 44 years',
 'Female; Estimate; SELECTED AGE CATEGORIES - 15 to 44 years',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 15 to 44 years',
 'Total; Estimate; SELECTED AGE CATEGORIES - 16 years and over',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 16 years and over',
 'Male; Estimate; SELECTED AGE CATEGORIES - 16 years and over',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 16 years and over',
 'Female; Estimate; SELECTED AGE CATEGORIES - 16 years and over',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 16 years and over',
 'Total; Estimate; SELECTED AGE CATEGORIES - 18 years and over',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 18 years and over',
 'Male; Estimate; SELECTED AGE CATEGORIES - 18 years and over',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 18 years and over',
 'Female; Estimate; SELECTED AGE CATEGORIES - 18 years and over',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 18 years and over',
 'Total; Estimate; SELECTED AGE CATEGORIES - 21 years and over',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 21 years and over',
 'Male; Estimate; SELECTED AGE CATEGORIES - 21 years and over',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 21 years and over',
 'Female; Estimate; SELECTED AGE CATEGORIES - 21 years and over',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 21 years and over',
 'Total; Estimate; SELECTED AGE CATEGORIES - 60 years and over',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 60 years and over',
 'Male; Estimate; SELECTED AGE CATEGORIES - 60 years and over',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 60 years and over',
 'Female; Estimate; SELECTED AGE CATEGORIES - 60 years and over',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 60 years and over',
 'Total; Estimate; SELECTED AGE CATEGORIES - 62 years and over',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 62 years and over',
 'Male; Estimate; SELECTED AGE CATEGORIES - 62 years and over',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 62 years and over',
 'Female; Estimate; SELECTED AGE CATEGORIES - 62 years and over',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 62 years and over',
 'Total; Estimate; SELECTED AGE CATEGORIES - 65 years and over',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 65 years and over',
 'Male; Estimate; SELECTED AGE CATEGORIES - 65 years and over',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 65 years and over',
 'Female; Estimate; SELECTED AGE CATEGORIES - 65 years and over',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 65 years and over',
 'Total; Estimate; SELECTED AGE CATEGORIES - 75 years and over',
 'Percent; Estimate; SELECTED AGE CATEGORIES - 75 years and over',
 'Male; Estimate; SELECTED AGE CATEGORIES - 75 years and over',
 'Percent Male; Estimate; SELECTED AGE CATEGORIES - 75 years and over',
 'Female; Estimate; SELECTED AGE CATEGORIES - 75 years and over',
 'Percent Female; Estimate; SELECTED AGE CATEGORIES - 75 years and over',
 'Total; Estimate; SUMMARY INDICATORS - Median age (years)',
 'Percent; Estimate; SUMMARY INDICATORS - Median age (years)',
 'Male; Estimate; SUMMARY INDICATORS - Median age (years)',
 'Percent Male; Estimate; SUMMARY INDICATORS - Median age (years)',
 'Female; Estimate; SUMMARY INDICATORS - Median age (years)',
 'Percent Female; Estimate; SUMMARY INDICATORS - Median age (years)',
 'Total; Estimate; SUMMARY INDICATORS - Sex ratio (males per 100 females)',
 'Percent; Estimate; SUMMARY INDICATORS - Sex ratio (males per 100 females)',
 'Male; Estimate; SUMMARY INDICATORS - Sex ratio (males per 100 females)',
 'Percent Male; Estimate; SUMMARY INDICATORS - Sex ratio (males per 100 females)',
 'Female; Estimate; SUMMARY INDICATORS - Sex ratio (males per 100 females)',
 'Percent Female; Estimate; SUMMARY INDICATORS - Sex ratio (males per 100 females)',
 'Total; Estimate; SUMMARY INDICATORS - Age dependency ratio',
 'Percent; Estimate; SUMMARY INDICATORS - Age dependency ratio',
 'Male; Estimate; SUMMARY INDICATORS - Age dependency ratio',
 'Percent Male; Estimate; SUMMARY INDICATORS - Age dependency ratio',
 'Female; Estimate; SUMMARY INDICATORS - Age dependency ratio',
 'Percent Female; Estimate; SUMMARY INDICATORS - Age dependency ratio',
 'Total; Estimate; SUMMARY INDICATORS - Old-age dependency ratio',
 'Percent; Estimate; SUMMARY INDICATORS - Old-age dependency ratio',
 'Male; Estimate; SUMMARY INDICATORS - Old-age dependency ratio',
 'Percent Male; Estimate; SUMMARY INDICATORS - Old-age dependency ratio',
 'Female; Estimate; SUMMARY INDICATORS - Old-age dependency ratio',
 'Percent Female; Estimate; SUMMARY INDICATORS - Old-age dependency ratio',
 'Total; Estimate; SUMMARY INDICATORS - Child dependency ratio',
 'Percent; Estimate; SUMMARY INDICATORS - Child dependency ratio',
 'Male; Estimate; SUMMARY INDICATORS - Child dependency ratio',
 'Percent Male; Estimate; SUMMARY INDICATORS - Child dependency ratio',
 'Female; Estimate; SUMMARY INDICATORS - Child dependency ratio',
 'Percent Female; Estimate; SUMMARY INDICATORS - Child dependency ratio',
 'Total; Estimate; PERCENT ALLOCATED - Sex',
 'Percent; Estimate; PERCENT ALLOCATED - Sex',
 'Male; Estimate; PERCENT ALLOCATED - Sex',
 'Percent Male; Estimate; PERCENT ALLOCATED - Sex',
 'Female; Estimate; PERCENT ALLOCATED - Sex',
 'Percent Female; Estimate; PERCENT ALLOCATED - Sex',
 'Total; Estimate; PERCENT ALLOCATED - Age',
 'Percent; Estimate; PERCENT ALLOCATED - Age',
 'Male; Estimate; PERCENT ALLOCATED - Age',
 'Percent Male; Estimate; PERCENT ALLOCATED - Age',
 'Female; Estimate; PERCENT ALLOCATED - Age',
 'Percent Female; Estimate; PERCENT ALLOCATED - Age']

In [ ]:
zcta -- zipcode map