In [10]:
import pandas as pd
import numpy as np
import datetime
import os
os.getcwd()

'/home/jian/Projects/Big_Lots/TMR/TMR_data/Up_to_2019Q2'

In [11]:
tmr_detail=pd.read_csv("./output/BL_MMM_long_cumu_up_to_2019Q2_JL_2019-11-15.csv",dtype=str)
tmr_detail.head(2)

,cleaned dma,click,cost,impression,media,placement,submedia,week date
0,"Los Angeles, CA",6687,309.818159116938,679747,Email,xx,xx,2016-09-25
1,"Dallas-Ft. Worth, TX",3185,147.56160522751262,323753,Email,xx,xx,2016-09-25

In [14]:
tmr_detail_Q2=tmr_detail[tmr_detail['week date']>="2019-05-05"]
tmr_detail_Q2['week date'].max()

'2019-07-28'

In [5]:
tmr_detail_Q2['impression']=tmr_detail_Q2['impression'].astype(int)
tmr_detail_Q2['click']=tmr_detail_Q2['click'].astype(int)
tmr_detail_Q2['cost']=tmr_detail_Q2['cost'].astype(float)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [6]:
tmr_detail_Q2[tmr_detail_Q2['submedia']=="Programmatic"].groupby("placement")['impression','click','cost'].sum().reset_index()

                          placement  impression   click           cost
0                 Custom Executions           0       0       0.000000
1                   Digital Display      569391   11731    5124.465000
2                     Digital Radio    15906092   15701  251088.341969
3                     Digital Video    15309319   31432  164555.107000
4                          Pre-Roll     4613867     124  127713.696233
5              Programmatic Display    14099289   49382   75018.656122
6  Programmatic Display Retargeting    51799487  293100  133499.867231
7               Programmatic Native    21719598  156236   67961.660000
8                Programmatic Video     3860884   30122   80162.038916

In [7]:
tmr_detail_Q2[tmr_detail_Q2['submedia']=="YouTube"].groupby(["submedia","placement"])['impression','click','cost'].sum().reset_index()

  submedia            placement  impression  click           cost
0  YouTube  Multiplatform Video    36931667  92546  271408.260334

In [8]:
tmr_detail_Q2['placement'].unique()

array(['Bing', 'Google', 'Twitter', 'Facebook/Instagram', 'Pinterest',
       'mobile audio', 'mobile display', 'Multiplatform Video',
       'Custom Executions', 'Digital Radio', 'Digital Video', 'Pre-Roll',
       'Programmatic Display', 'Programmatic Display Retargeting',
       'Programmatic Native', 'Programmatic Video', 'Digital Display',
       'xx', 'Hosted', 'Flipp App', 'Native Network', 'BRAV', 'E!',
       'FOOD', 'HALL', 'HGTV', 'HMM', 'ID', 'ION', 'LIF', 'NAN', 'VH1',
       'BET', 'TVL'], dtype=object)

In [9]:
tmr_detail_Q2[tmr_detail_Q2['placement'].str.contains("mobile")]

,cleaned dma,click,cost,impression,media,placement,submedia,week date
3483790,NaN,0,2156.24,107812,Digital,mobile audio,Pandora,2019-07-28
3483791,NaN,87,0.00,0,Digital,mobile display,Pandora,2019-07-28
3483792,NaN,0,5469.66,273483,Digital,mobile audio,Pandora,2019-07-21
3483793,NaN,229,0.00,0,Digital,mobile display,Pandora,2019-07-21
3483794,NaN,0,9072.02,453601,Digital,mobile audio,Pandora,2019-07-14
3483795,NaN,418,0.00,0,Digital,mobile display,Pandora,2019-07-14
3483796,NaN,567,0.00,0,Digital,mobile display,Pandora,2019-07-07
3483797,NaN,0,13804.08,690204,Digital,mobile audio,Pandora,2019-07-07
3483798,NaN,0,10817.80,540890,Digital,mobile audio,Pandora,2019-06-30
3483799,NaN,530,0.00,0,Digital,mobile display,Pandora,2019-06-30
3483800,NaN,1026,0.00,0,Digital,mobile display,Pandora,2019-06-23
3483801,NaN,0,24334.84,1216742,Digital,mobile audio,Pandora,2019-06-23
3483802,NaN,0,9376.60,468830,Digital,mobile audio,Pandora,2019-06-16
3483803,NaN,319,0.00,0,Digital,mobile display,Pandora,2019-06-16
3483804,NaN,292,0.00,0,Digital,mobile display,Pandora,2019-06-09
3483805,NaN,0,6752.92,337646,Digital,mobile audio,Pandora,2019-06-09
3483806,NaN,631,0.00,0,Digital,mobile display,Pandora,2019-06-02
3483807,NaN,0,13804.24,690212,Digital,mobile audio,Pandora,2019-06-02
3483808,NaN,0,11923.64,596182,Digital,mobile audio,Pandora,2019-05-26
3483809,NaN,571,0.00,0,Digital,mobile display,Pandora,2019-05-26
3483810,NaN,311,0.00,0,Digital,mobile display,Pandora,2019-05-19
3483811,NaN,0,7235.76,361788,Digital,mobile audio,Pandora,2019-05-19
3483812,NaN,298,0.00,0,Digital,mobile display,Pandora,2019-05-12
3483813,NaN,0,7821.14,391057,Digital,mobile audio,Pandora,2019-05-12
3483814,NaN,289,0.00,0,Digital,mobile display,Pandora,2019-05-05
3483815,NaN,0,6132.02,306601,Digital,mobile audio,Pandora,2019-05-05