In [1]:
import os
import datetime
import shutil
import glob
import pandas as pd

In [2]:
original_folder_impression="/mnt/clients/juba/hqjubaapp02/jliang/Projects/Big_Lots/Predictive_Model/LR_returned_files/impressions/"
original_folder_click="/mnt/clients/juba/hqjubaapp02/jliang/Projects/Big_Lots/Predictive_Model/LR_returned_files/clicks/"
original_folder_act="/mnt/clients/juba/hqjubaapp02/jliang/Projects/Big_Lots/Predictive_Model/LR_returned_files/activities/"

In [22]:
def check_dcm_file_range(folder):
    list_all_files=glob.glob(folder+"*")
    list_all_dates=[x.split('dcm_account7252_')[1].split('_')[1][:8] for x in list_all_files]
    list_all_dates=[x for x in list_all_dates if x.isdigit()]
    list_all_dates=list(set(list_all_dates))
    min_date=min(list_all_dates)
    max_date=max(list_all_dates)
    unique_date=len(set([x for x in list_all_dates if x.isdigit()]))
    day_diff=(datetime.datetime.strptime(max_date,"%Y%m%d")-datetime.datetime.strptime(min_date,"%Y%m%d")).days+1
    
    list_0_should_be_all=[]
    for i in range(day_diff):
        list_0_should_be_all.append(str((datetime.datetime.strptime(min_date,"%Y%m%d")+datetime.timedelta(days=i)).date()).replace("-",""))
    list_0_should_be_all.sort()
    list_all_dates.sort()

    list_missing=[x for x in list_0_should_be_all if x not in list_all_dates]
    print(folder)
    print("total_len: %i"%len(list_all_files))
    print("min_date: %s"%min_date)
    print("max_date: %s"%max_date)
    print("unique_date:%i"%unique_date)
    print("day_diff: %i"%day_diff)
    print("list_missing",list_missing)

In [23]:
check_dcm_file_range(original_folder_impression)

/mnt/clients/juba/hqjubaapp02/jliang/Projects/Big_Lots/Predictive_Model/LR_returned_files/impressions/
total_len: 10023
min_date: 20180524
max_date: 20200502
unique_date:693
day_diff: 710
list_missing ['20190125', '20190126', '20190127', '20190128', '20190129', '20190130', '20190131', '20190201', '20190202', '20200123', '20200124', '20200125', '20200126', '20200127', '20200128', '20200129', '20200201']

In [24]:
check_dcm_file_range(original_folder_click)

/mnt/clients/juba/hqjubaapp02/jliang/Projects/Big_Lots/Predictive_Model/LR_returned_files/clicks/
total_len: 9965
min_date: 20180524
max_date: 20200502
unique_date:701
day_diff: 710
list_missing ['20190125', '20190126', '20190127', '20190128', '20190129', '20190130', '20190131', '20190201', '20190202']

In [25]:
check_dcm_file_range(original_folder_act)

/mnt/clients/juba/hqjubaapp02/jliang/Projects/Big_Lots/Predictive_Model/LR_returned_files/activities/
total_len: 794
min_date: 20180524
max_date: 20200502
unique_date:707
day_diff: 710
list_missing ['20181010', '20181015', '20190104']

In [5]:
new_folder_impression="/"

In [7]:
df=pd.read_csv(list_act[0],nrows=100,sep="\t")
df

,Customer_Link,Event Time,Advertiser ID,Campaign ID,Ad ID,Rendering ID,Creative Version,Site ID (DCM),Placement ID,Country Code,...,DBM Media Fee 4 (Advertiser Currency),DBM Media Fee 5 (USD),DBM Media Fee 5 (Partner Currency),DBM Media Fee 5 (Advertiser Currency),DBM Data Fees (USD),DBM Data Fees (Partner Currency),DBM Data Fees (Advertiser Currency),DBM Billable Cost (USD),DBM Billable Cost (Partner Currency),DBM Billable Cost (Advertiser Currency)
0,Xi14680y3jJSefERimCSaGyy5rG3H1qAbHotFXIvHiN1P4...,1532297068107159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,...,0,0,0,0,0,0,0,0,0,0
1,UNMATCHED,1532293926986239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,...,0,0,0,0,0,0,0,0,0,0
2,UNMATCHED,1532264074368743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,...,0,0,0,0,0,0,0,0,0,0
3,UNMATCHED,1532308249844970,8095847.0,21227830.0,423301117.0,0.0,0.0,1291657.0,225086861.0,US,...,0,0,0,0,0,0,0,0,0,0
4,UNMATCHED,1532273177987112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,UNMATCHED,1532280237968831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NL,...,0,0,0,0,0,0,0,0,0,0
96,XY1468rOewzcTJ316pmRLT24xeEtCU_Ar5fdFfVvxo1KGLRjo,1532269467644100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,...,0,0,0,0,0,0,0,0,0,0
97,UNMATCHED,1532314356793736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,...,0,0,0,0,0,0,0,0,0,0
98,XY1468xjN8kETsKNO2ZA9ylH3mP6w6BgSaPa1mhf5kajzVvrg,1532265494373176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,...,0,0,0,0,0,0,0,0,0,0
99,XY14683QhkP1dQnfIqzEIDczfTF7VdCPolZcqXKg9oADMmEhs,1532279982507477,8095847.0,20836313.0,414888750.0,0.0,0.0,1234535.0,215929001.0,US,...,0,0,0,0,0,0,0,0,0,0

In [20]:
list_act[0]

'/'