In [1]:
import datetime
datetime.datetime.now().date().weekday()

1

In [39]:
today_date_weekday=datetime.datetime.now().date().weekday()
recent_monday=datetime.datetime.now().date()-datetime.timedelta(days=today_date_weekday%7)
recent_monday

datetime.date(2019, 9, 2)

In [43]:
test_day=datetime.date(2019,9,10)
today_date_weekday=test_day.weekday()
recent_monday=test_day-datetime.timedelta(days=today_date_weekday%7)
recent_monday

datetime.date(2019, 9, 9)

In [20]:
datetime.date(2019,9,1).day

1

In [21]:
import pandas as pd

In [22]:
rfa_mapping=pd.read_excel("/home/jian/Projects/Smoothie_King/SK_celery/RFA_region_20190128.xlsx",dtype=str)

In [23]:
rfa_mapping.shape

(1036, 10)

In [26]:
rfa_mapping

,Store: Store Number â†‘,Address,City,State/Province,Zip/Postal Code,Open Date,Status,DMA,Co-Op/Regional,Field Marketing Manager
0,0000,7215 Veterans Memorial Blvd.,Metairie,Louisiana,70003,1973-07-07 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
1,0002,4539 Veterans Blvd.,Metairie,Louisiana,70006,1989-09-11 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
2,0003,"1000 S. Clearview Pkwy., Suite 1004",Harahan,Louisiana,70123,1989-11-13 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
3,0004,"6600 Franklin Ave., #A-11",New Orleans,Louisiana,70122,1993-08-09 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
4,0005,"5300 Tchoupitoulas St., #D-4",New Orleans,Louisiana,70115,1990-04-16 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
5,0006,"4041 Williams Blvd., Ste. 4-A",Kenner,Louisiana,70065,1990-05-18 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
6,0007,900-A Terry Parkway,Terrytown,Louisiana,70056,1990-07-30 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
7,0009,533 Gause Blvd,Slidell,Louisiana,70458,1990-08-27 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
8,0010,1461 Veterans Memorial Blvd.,Metairie,Louisiana,70005,1990-07-27 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
9,0011,"12519 Airline Highway, Ste I",Destrehan,Louisiana,70047,1990-09-17 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
10,0013,404 West University Ave.,Hammond,Louisiana,70401,1991-01-21 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
11,0014,"2222 Clearview Pkwy., Ste. G",Metairie,Louisiana,70001,1991-01-06 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
12,0015,6221 S. Claiborne Ave.,New Orleans,Louisiana,70125,1991-02-11 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
13,0016,4300 Ryan St.,Lake Charles,Louisiana,70605,1991-05-10 00:00:00,Open,Lake Charles,nan,Sara Dowd
14,0020,3366 Paris Rd.,Chalmette,Louisiana,70043,1992-02-17 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
15,0022,1830 North Causeway Approach,Mandeville,Louisiana,70471,1992-06-22 00:00:00,Open â€“ Transfer in Progress,New Orleans,New Orleans,Sara Dowd
16,0023,1991-B Barataria Blvd.,Marrero,Louisiana,70072,1992-10-26 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
17,0024,4509 FM 1960 West,Houston,Texas,77069,1992-08-24 00:00:00,Open,Houston,Houston,Jordan Stinnett
18,0025,3865 General DeGaulle Dr. Ste. B,New Orleans,Louisiana,70114,1993-04-12 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
19,0027,"9401 Jefferson Hwy, Ste C",River Ridge,Louisiana,70123,1993-02-22 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
20,0028,1506 West Airline Hwy,LaPlace,Louisiana,70068,1993-03-08 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
21,0029,7673 Perkins Rd,Baton Rouge,Louisiana,70810,1993-06-21 00:00:00,Open,Baton Rouge,Baton Rouge,Sara Dowd
22,0030,5410 Kirby,Houston,Texas,77005,2006-04-07 00:00:00,Open,Houston,Houston,Jordan Stinnett
23,0031,8050 Crowder Blvd.,New Orleans,Louisiana,70127,1995-03-19 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
24,0032,1052 W Tunnel Blvd,Houma,Louisiana,70364,1993-12-20 00:00:00,Open,New Orleans,nan,Sara Dowd
25,0033,5300 Richmond Ave.,Houston,Texas,77056,1993-08-23 00:00:00,Open,Houston,Houston,Jordan Stinnett
26,0040,12513-B Westheimer,Houston,Texas,77077,1994-10-24 00:00:00,Open,Houston,Houston,Jordan Stinnett
27,0042,1525 Alton Rd.,Miami Beach,Florida,33139,1994-02-14 00:00:00,Open,Miami-Ft. Lauderdale,Miami-Ft. Lauderdale,Kimberly Brandon
28,0045,1270 West Paces Ferry Road NW,Atlanta,Georgia,30324,1994-04-04 00:00:00,Open,Atlanta,Atlanta,Kimberly Brandon
29,0046,"12531 Hwy. 90, Unit C",Luling,Louisiana,70070,1994-04-25 00:00:00,Open,New Orleans,New Orleans,Sara Dowd
...,...,...,...,...,...,...,...,...,...,...
1006,8138,Yeouido IFC Mall,nan,nan,nan,2012-08-30 00:00:00,Open,nan,nan,nan
1007,8139,Lottemart Junggye,nan,nan,nan,2012-09-19 00:00:00,Open,nan,nan,nan
1008,8140,Gasan Mario outlet,nan,nan,nan,2012-09-21 00:00:00,Open,nan,nan,nan
1009,8141,Gumi Wonpyong,nan,nan,nan,2012-09-26 00:00:00,Open,nan,nan,nan
1010,8142,Itaewon,nan,nan,nan,2012-09-30 00:00:00,Open,nan,nan,nan
1011,8143,Incheon Squareone,nan,nan,nan,2012-10-05 00:00:00,Open,nan,nan,nan
1012,8144,Daegu Lottecinema plaza,nan,nan,nan,2012-10-19 00:00:00,Open,nan,nan,nan
1013,8145,Lottemart Chungju Biha,nan,nan,nan,2012-11-08 00:00:00,Open,nan,nan,nan
1014,8146,Serosu Gil,nan,nan,nan,2012-12-14 00:00:00,Open,nan,nan,nan
1015,8147,Wonjuterminal,nan,nan,nan,2013-02-03 00:00:00,Open,nan,nan,nan
1016,8148,Seoul Square,nan,nan,nan,2013-02-26 00:00:00,Open,nan,nan,nan
1017,8149,Lotte Bigmarket Dobong,nan,nan,nan,2013-02-28 00:00:00,Open,nan,nan,nan
1018,8150,Lotte Jungdong,nan,nan,nan,2013-03-05 00:00:00,Open,nan,nan,nan
1019,8151,ilsan One Mount,nan,nan,nan,2013-03-29 00:00:00,Open,nan,nan,nan
1020,8152,Jinju Gyeongsang Univ,nan,nan,nan,2013-04-24 00:00:00,Open,nan,nan,nan
1021,8153,Gwangju Chungjang YZ Park,nan,nan,nan,2013-04-26 00:00:00,Open,nan,nan,nan
1022,8154,Goyang International Horticulture 1,nan,nan,nan,2013-04-27 00:00:00,Open,nan,nan,nan
1023,8155,Goyang International Horticulture 2,nan,nan,nan,2013-04-27 00:00:00,Open,nan,nan,nan
1024,8156,Ulsan Upsquare,nan,nan,nan,2013-05-10 00:00:00,Open,nan,nan,nan
1025,8157,Lotte FITIN Dondgdaemun,nan,nan,nan,2013-05-31 00:00:00,Open,nan,nan,nan
1026,8158,Ilsan Zenith,nan,nan,nan,2013-05-31 00:00:00,Open,nan,nan,nan
1027,8159,Lotte Gimhae Outlet,nan,nan,nan,2013-06-28 00:00:00,Open,nan,nan,nan
1028,8160,Bupyeong CGV,nan,nan,nan,2013-07-05 00:00:00,Open,nan,nan,nan
1029,8161,Songdo Canalwalk,nan,nan,nan,2013-07-17 00:00:00,Open,nan,nan,nan
1030,8162,Jangan Bauhaus,nan,nan,nan,2013-08-14 00:00:00,Open,nan,nan,nan
1031,8163,Busan Premium Outlet 1,nan,nan,nan,2013-08-29 00:00:00,Open,nan,nan,nan
1032,8164,Busan Premium Outlet 2,nan,nan,nan,2013-08-29 00:00:00,Open,nan,nan,nan
1033,8165,Buson Lotte,nan,nan,nan,2013-10-04 00:00:00,Open,nan,nan,nan
1034,8166,Chuncheon Myeongdong,nan,nan,nan,2013-09-06 00:00:00,Open,nan,nan,nan
1035,8750,"Galleria Plaza, Unit 30",George Town,nan,nan,2010-12-02 00:00:00,Open,nan,nan,nan

In [28]:
rfa_mapping.shape

(1036, 3)