In [1]:
import pandas as pd
import os
os.getcwd()

'/home/jian/Projects/Big_Lots/Analysis/2018_Q4/Mattress'

In [2]:
mattress_data=pd.read_table("/home/jian/Projects/Big_Lots/Analysis/2018_Q4/Mattress/MediaStorm Matress Sales (subclasses 61501 - 61505) by Subclass 2017-06-03 - 2018-02-03.txt",
                           dtype=str,sep="|")

mattress_data.shape

(1103929, 8)

In [13]:
mattress_data['class_code_id'].unique()

array(['61501', '61503', '61504', '61502', '61505'], dtype=object)

In [9]:
daily_data=pd.read_table("/home/jian/BigLots/MediaStorm_2018-10-27/MediaStormDailySales20181030-112403-266.txt",
                         dtype=str,sep="|")
daily_data.head(2)

,location_id,transaction_dt,transaction_id,customer_id_hashed,class_code_id,subclass_id,subclass_transaction_units,subclass_transaction_amt
0,4644,2018-10-23,2398,NaN,12009,4,1,00000000000003.0000
1,1831,2018-10-27,8849,f6c4cf6d10be912f9bea2066c9e011f2871f41c1d76525...,61203,3,1,00000000000099.9900

In [7]:
sorted(mattress_data['transaction_dt'].unique())

['2017-06-03',
 '2017-06-04',
 '2017-06-05',
 '2017-06-06',
 '2017-06-07',
 '2017-06-08',
 '2017-06-09',
 '2017-06-10',
 '2017-06-11',
 '2017-06-12',
 '2017-06-13',
 '2017-06-14',
 '2017-06-15',
 '2017-06-16',
 '2017-06-17',
 '2017-06-18',
 '2017-06-19',
 '2017-06-20',
 '2017-06-21',
 '2017-06-22',
 '2017-06-23',
 '2017-06-24',
 '2017-06-25',
 '2017-06-26',
 '2017-06-27',
 '2017-06-28',
 '2017-06-29',
 '2017-06-30',
 '2017-07-01',
 '2017-07-02',
 '2017-07-03',
 '2017-07-04',
 '2017-07-05',
 '2017-07-06',
 '2017-07-07',
 '2017-07-08',
 '2017-07-09',
 '2017-07-10',
 '2017-07-11',
 '2017-07-12',
 '2017-07-13',
 '2017-07-14',
 '2017-07-15',
 '2017-07-16',
 '2017-07-17',
 '2017-07-18',
 '2017-07-19',
 '2017-07-20',
 '2017-07-21',
 '2017-07-22',
 '2017-07-23',
 '2017-07-24',
 '2017-07-25',
 '2017-07-26',
 '2017-07-27',
 '2017-07-28',
 '2017-07-29',
 '2017-07-30',
 '2017-07-31',
 '2017-08-01',
 '2017-08-02',
 '2017-08-03',
 '2017-08-04',
 '2017-08-05',
 '2017-08-06',
 '2017-08-07',
 '2017-08-08',
 '2017-08-09',
 '2017-08-10',
 '2017-08-11',
 '2017-08-12',
 '2017-08-13',
 '2017-08-14',
 '2017-08-15',
 '2017-08-16',
 '2017-08-17',
 '2017-08-18',
 '2017-08-19',
 '2017-08-20',
 '2017-08-21',
 '2017-08-22',
 '2017-08-23',
 '2017-08-24',
 '2017-08-25',
 '2017-08-26',
 '2017-08-27',
 '2017-08-28',
 '2017-08-29',
 '2017-08-30',
 '2017-08-31',
 '2017-09-01',
 '2017-09-02',
 '2017-09-03',
 '2017-09-04',
 '2017-09-05',
 '2017-09-06',
 '2017-09-07',
 '2017-09-08',
 '2017-09-09',
 '2017-09-10',
 '2017-09-11',
 '2017-09-12',
 '2017-09-13',
 '2017-09-14',
 '2017-09-15',
 '2017-09-16',
 '2017-09-17',
 '2017-09-18',
 '2017-09-19',
 '2017-09-20',
 '2017-09-21',
 '2017-09-22',
 '2017-09-23',
 '2017-09-24',
 '2017-09-25',
 '2017-09-26',
 '2017-09-27',
 '2017-09-28',
 '2017-09-29',
 '2017-09-30',
 '2017-10-01',
 '2017-10-02',
 '2017-10-03',
 '2017-10-04',
 '2017-10-05',
 '2017-10-06',
 '2017-10-07',
 '2017-10-08',
 '2017-10-09',
 '2017-10-10',
 '2017-10-11',
 '2017-10-12',
 '2017-10-13',
 '2017-10-14',
 '2017-10-15',
 '2017-10-16',
 '2017-10-17',
 '2017-10-18',
 '2017-10-19',
 '2017-10-20',
 '2017-10-21',
 '2017-10-22',
 '2017-10-23',
 '2017-10-24',
 '2017-10-25',
 '2017-10-26',
 '2017-10-27',
 '2017-10-28',
 '2017-10-29',
 '2017-10-30',
 '2017-10-31',
 '2017-11-01',
 '2017-11-02',
 '2017-11-03',
 '2017-11-04',
 '2017-11-05',
 '2017-11-06',
 '2017-11-07',
 '2017-11-08',
 '2017-11-09',
 '2017-11-10',
 '2017-11-11',
 '2017-11-12',
 '2017-11-13',
 '2017-11-14',
 '2017-11-15',
 '2017-11-16',
 '2017-11-17',
 '2017-11-18',
 '2017-11-19',
 '2017-11-20',
 '2017-11-21',
 '2017-11-22',
 '2017-11-23',
 '2017-11-24',
 '2017-11-25',
 '2017-11-26',
 '2017-11-27',
 '2017-11-28',
 '2017-11-29',
 '2017-11-30',
 '2017-12-01',
 '2017-12-02',
 '2017-12-03',
 '2017-12-04',
 '2017-12-05',
 '2017-12-06',
 '2017-12-07',
 '2017-12-08',
 '2017-12-09',
 '2017-12-10',
 '2017-12-11',
 '2017-12-12',
 '2017-12-13',
 '2017-12-14',
 '2017-12-15',
 '2017-12-16',
 '2017-12-17',
 '2017-12-18',
 '2017-12-19',
 '2017-12-20',
 '2017-12-21',
 '2017-12-22',
 '2017-12-23',
 '2017-12-24',
 '2017-12-26',
 '2017-12-27',
 '2017-12-28',
 '2017-12-29',
 '2017-12-30',
 '2017-12-31',
 '2018-01-01',
 '2018-01-02',
 '2018-01-03',
 '2018-01-04',
 '2018-01-05',
 '2018-01-06',
 '2018-01-07',
 '2018-01-08',
 '2018-01-09',
 '2018-01-10',
 '2018-01-11',
 '2018-01-12',
 '2018-01-13',
 '2018-01-14',
 '2018-01-15',
 '2018-01-16',
 '2018-01-17',
 '2018-01-18',
 '2018-01-19',
 '2018-01-20',
 '2018-01-21',
 '2018-01-22',
 '2018-01-23',
 '2018-01-24',
 '2018-01-25',
 '2018-01-26',
 '2018-01-27',
 '2018-01-28',
 '2018-01-29',
 '2018-01-30',
 '2018-01-31',
 '2018-02-01',
 '2018-02-02',
 '2018-02-03']

In [10]:
daily_data.shape

(11275984, 8)