In [1]:
import pandas as pd
import numpy as np
import os
import glob
import datetime
import gc
import hashlib
import gc
from sqlalchemy import create_engine
import sqlalchemy

print(datetime.datetime.now())

2020-01-03 10:41:29.076822

In [2]:
# Checking all old file columns
samplerows=None

def recursive_file_gen(root_path):
    for root, dirs, files in os.walk(root_path):
        for file in files:
            yield os.path.join(root,file)

In [3]:
file_path="/home/jian/Projects/Big_Lots/Loyal_members/loyalty_register_data/MediaStorm_Lapsed_Reward_Member_Master_from2014-08-26to2017-02-26.zip"
data_0=pd.read_table(file_path,dtype=str,sep="|",compression="zip",nrows=samplerows)

col_list=data_0.columns.tolist()

print("data_0.shape",data_0.shape)
print("data_0['customer_id_hashed'].nunique()",data_0['customer_id_hashed'].nunique())
print("data_0['sign_up_date'].min()",data_0['sign_up_date'].min())
print("data_0['sign_up_date'].max()",data_0['sign_up_date'].max())
data_0['file_path']=file_path
data_0.head(2)

data_0.shape (1983373, 13)
data_0['customer_id_hashed'].nunique() 1873409
data_0['sign_up_date'].min() 2014-08-26
data_0['sign_up_date'].max() 2017-02-26

,customer_id_hashed,email_address_hash,sign_up_date,sign_up_channel,sign_up_location,customer_zip_code,transaction_count,transaction_amount,experian_multi_cluster,experian_demo_cluster,purchase_channel,email_unsubscribe_indicator,email_undeliverable_indicator,file_path
0,29941ea4279e5d81bd1880d7e069baf8a79d8d1c1b0caf...,fb43c45617989a3acc98c467d08bb91a78aef369c2526d...,2015-01-12,STORE,5140,36608,4,95.60,1,1,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...
1,edf57f913e712e590f86c186c5139a13beedd834b3bff9...,32993808bf4dc785e1c4d10bca85af35e16dc282313792...,2016-10-02,ONLINE,NaN,95124,4,134.05,2,1,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...

In [4]:
file_path="/home/jian/Projects/Big_Lots/Loyal_members/loyalty_register_data/MediaStormCustTot-hashed-email.txt"
data_1=pd.read_csv(file_path,dtype=str,header=None,error_bad_lines=False,warn_bad_lines=True,nrows=samplerows) # sep=","
data_1.columns=col_list # assign column names
data_1['customer_id_hashed']=data_1['customer_id_hashed'].apply(lambda x: hashlib.sha256(x.encode('utf-8')).hexdigest())
print("data_1.shape",data_1.shape)
print("data_1['customer_id_hashed'].nunique()",data_1['customer_id_hashed'].nunique())
print("data_1['sign_up_date'].min()",data_1['sign_up_date'].min())
print("data_1['sign_up_date'].max()",data_1['sign_up_date'].max())
data_1['file_path']=file_path
data_1.head(2)

b'Skipping line 12372214: expected 13 fields, saw 14\n'
b'Skipping line 12519622: expected 13 fields, saw 14\n'
b'Skipping line 19001869: expected 13 fields, saw 14\n'

data_1.shape (19337594, 13)
data_1['customer_id_hashed'].nunique() 17807233
data_1['sign_up_date'].min() ,2010-11-05"
data_1['sign_up_date'].max() 2018-01-08

,customer_id_hashed,email_address_hash,sign_up_date,sign_up_channel,sign_up_location,customer_zip_code,transaction_count,transaction_amount,experian_multi_cluster,experian_demo_cluster,purchase_channel,email_unsubscribe_indicator,email_undeliverable_indicator,file_path
0,c446cbd9d237d676d038e98b22ff891bbf48c00d3a21ee...,9a636febd7cdd10fcb4d2dd8a716cd5278cf51f3683503...,2017-04-01,STORE,4672,98403,000000000000001.,0000000000000036.68,0,0,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...
1,f1b909c22db55b10d182fbc5ae7f61f6f77155ca1dd806...,60573729f6ecad9eed81fe50100e601f78a314d9e3f83f...,2016-05-29,STORE,5103,21218,000000000000004.,0000000000000411.69,5,1,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...

In [5]:
file_path='/home/jian/Projects/Big_Lots/Loyal_members/loyalty_register_data/Existing Reward Member Master as of 2018-06-05.txt'
data_2=pd.read_csv(file_path,dtype=str,sep='|',nrows=samplerows)

print(data_2.columns.tolist()==col_list)
print("data_2.shape",data_2.shape)
print("data_2['customer_id_hashed'].nunique()",data_2['customer_id_hashed'].nunique())
print("data_2['sign_up_date'].min()",data_2['sign_up_date'].min())
print("data_2['sign_up_date'].max()",data_2['sign_up_date'].max())
data_2['file_path']=file_path
data_2.head(2)

True
data_2.shape (5759051, 13)
data_2['customer_id_hashed'].nunique() 5209279
data_2['sign_up_date'].min() 2009-08-08
data_2['sign_up_date'].max() 2018-03-31

,customer_id_hashed,email_address_hash,sign_up_date,sign_up_channel,sign_up_location,customer_zip_code,transaction_count,transaction_amount,experian_multi_cluster,experian_demo_cluster,purchase_channel,email_unsubscribe_indicator,email_undeliverable_indicator,file_path
0,1159b8e6e859966ed71e0269981b83d8af76784b39468a...,42888c563852b61c1695bed6da690ddcdcceae38312492...,2018-03-10,STORE,1701,70835,2,110.70,NaN,NaN,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...
1,a639202063f12c1fd06ff499516d344aa9ef2c43ac4647...,8a5092c658ca671c4ad6d9b2ac87fb884fa0e37c03757b...,2013-11-15,STORE,4643,55112,2,102.06,4,2,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...

In [6]:
file_path='/home/jian/Projects/Big_Lots/Loyal_members/loyalty_register_data/MediaStormCustomerTransactionTotals_2018-01-09_2018-03-31.txt'
data_3=pd.read_csv(file_path,nrows=samplerows,sep =',',dtype=str)
print(data_3.columns.tolist()==col_list)
print("data_3.shape",data_3.shape)
print("data_3['customer_id_hashed'].nunique()",data_3['customer_id_hashed'].nunique())
print("data_3['sign_up_date'].min()",data_3['sign_up_date'].min())
print("data_3['sign_up_date'].max()",data_3['sign_up_date'].max())
data_3['file_path']=file_path
data_3.head(2)

True
data_3.shape (7255226, 13)
data_3['customer_id_hashed'].nunique() 6623479
data_3['sign_up_date'].min() 2009-08-04
data_3['sign_up_date'].max() 2018-04-01

,customer_id_hashed,email_address_hash,sign_up_date,sign_up_channel,sign_up_location,customer_zip_code,transaction_count,transaction_amount,experian_multi_cluster,experian_demo_cluster,purchase_channel,email_unsubscribe_indicator,email_undeliverable_indicator,file_path
0,24369a2ea17c25adfd6768d76bc88cd40ef57afad3b268...,60c4ee00b61b5cf800e24e0dc443424c5c111ca1573047...,2012-10-29,STORE,1205,38464,2,10.13,NaN,NaN,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...
1,a639202063f12c1fd06ff499516d344aa9ef2c43ac4647...,8a5092c658ca671c4ad6d9b2ac87fb884fa0e37c03757b...,2013-11-15,STORE,4643,55112,4,131.79,4,2,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...

In [7]:
file_path='/home/jian/Projects/Big_Lots/Loyal_members/loyalty_register_data/New Reward Member Master as of 2018-06-05.txt'
data_4=pd.read_csv(file_path,dtype=str,sep='|',nrows=samplerows)

print(data_4.columns.tolist()==col_list)
print("data_4.shape",data_4.shape)
print("data_4['customer_id_hashed'].nunique()",data_4['customer_id_hashed'].nunique())
print("data_4['sign_up_date'].min()",data_4['sign_up_date'].min())
print("data_4['sign_up_date'].max()",data_4['sign_up_date'].max())
data_4['file_path']=file_path
data_4.head(2)

True
data_4.shape (659127, 13)
data_4['customer_id_hashed'].nunique() 659127
data_4['sign_up_date'].min() 2018-04-01
data_4['sign_up_date'].max() 2018-05-31

,customer_id_hashed,email_address_hash,sign_up_date,sign_up_channel,sign_up_location,customer_zip_code,transaction_count,transaction_amount,experian_multi_cluster,experian_demo_cluster,purchase_channel,email_unsubscribe_indicator,email_undeliverable_indicator,file_path
0,c5f8d2430eb408606c01baee8c129588834b5f1a6c259a...,89749bb10a3ffbc0199f9532c6c6afe7d2bb918e8c8176...,2018-05-17,STORE,5322,36542,1,167.80,NaN,NaN,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...
1,cef33684f5ee891765c65e3c3110be51caef61cbcfe45c...,b7893e3392c39ae6a64570dbf4ccbf3bd33de89cadb6a1...,2018-04-28,STORE,1296,27030,2,83.99,NaN,NaN,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...

In [8]:
file_path="/home/jian/BigLots/New_Sing_Ups_2018_Fiscal_Year/All Rewards Members 2018-02-04 - 2019-05-04.zip"
data_5=pd.read_csv(file_path,compression="zip",dtype=str,sep="|")

print(data_5.columns.tolist()==col_list)
print("data_5.shape",data_5.shape)
print("data_5['customer_id_hashed'].nunique()",data_5['customer_id_hashed'].nunique())
print("data_5['sign_up_date'].min()",data_5['sign_up_date'].min())
print("data_5['sign_up_date'].max()",data_5['sign_up_date'].max())
data_5['file_path']=file_path
data_5.head(2)

True
data_5.shape (7888562, 13)
data_5['customer_id_hashed'].nunique() 7888544
data_5['sign_up_date'].min() 2018-02-04
data_5['sign_up_date'].max() 2019-05-04

,customer_id_hashed,email_address_hash,sign_up_date,sign_up_channel,sign_up_location,customer_zip_code,transaction_count,transaction_amount,experian_multi_cluster,experian_demo_cluster,purchase_channel,email_unsubscribe_indicator,email_undeliverable_indicator,file_path
0,67c70ef098e439b3ee77aa1e12d067389ee58de68d82f2...,91b604fbb6382c0d4d9de79abd99c90376486500792900...,2018-11-06,STORE,811,30542,NaN,NaN,NaN,NaN,NaN,N,N,/home/jian/BigLots/New_Sing_Ups_2018_Fiscal_Ye...
1,1bba86339a713fa02fa3289fc001958fb292a6a9b74414...,f1d534c223352de706828a36e199c647a5acddb2667078...,2018-07-10,STORE,1961,29732,NaN,NaN,NaN,NaN,NaN,N,N,/home/jian/BigLots/New_Sing_Ups_2018_Fiscal_Ye...

In [9]:
file_path="/home/jian/BigLots/New_Sing_Ups_2018_Fiscal_Year/MediaStorm Rewards Master P4 2019 - no transaction info.zip"
data_6=pd.read_csv(file_path,compression="zip",dtype=str,sep="|")

print(data_6.columns.tolist()==col_list)
print("data_6.shape",data_6.shape)
print("data_6['customer_id_hashed'].nunique()",data_6['customer_id_hashed'].nunique())
print("data_6['sign_up_date'].min()",data_6['sign_up_date'].min())
print("data_6['sign_up_date'].max()",data_6['sign_up_date'].max())
data_6['file_path']=file_path
data_6.head(2)

True
data_6.shape (461199, 13)
data_6['customer_id_hashed'].nunique() 461195
data_6['sign_up_date'].min() 2019-05-05
data_6['sign_up_date'].max() 2019-06-01

,customer_id_hashed,email_address_hash,sign_up_date,sign_up_channel,sign_up_location,customer_zip_code,transaction_count,transaction_amount,experian_multi_cluster,experian_demo_cluster,purchase_channel,email_unsubscribe_indicator,email_undeliverable_indicator,file_path
0,a30cc90d9c489ad7f0ab223ba7ea0917dcc74e0bc7ff51...,5490ee7d4b0dd4fb12b58e05a3144502ca0aa3fb1f5aa9...,2019-05-13,STORE,1461,31904,NaN,NaN,NaN,NaN,NaN,N,N,/home/jian/BigLots/New_Sing_Ups_2018_Fiscal_Ye...
1,ba076e9261ef546379354f54e5a9f37a1fd570342a5635...,a2b9694fb1794949d935426fc4fe42df5ce01e2eea12af...,2019-05-16,STORE,4286,91352,NaN,NaN,NaN,NaN,NaN,N,N,/home/jian/BigLots/New_Sing_Ups_2018_Fiscal_Ye...

In [10]:
# Included in the "/home/jian/BigLots/" loop
'''
file_path='/home/jian/Projects/Big_Lots/Loyal_members/loyalty_register_data/New Reward Member Master as of 2018-07-03.txt'
data_7=pd.read_csv(file_path,dtype=str,sep='|',nrows=samplerows)

print(data_7.columns.tolist()==col_list)
print("data_7.shape",data_7.shape)
print("data_7['customer_id_hashed'].nunique()",data_7['customer_id_hashed'].nunique())
print("data_7['sign_up_date'].min()",data_7['sign_up_date'].min())
print("data_7['sign_up_date'].max()",data_7['sign_up_date'].max())
data_7['file_path']=file_path
data_7.head(2)
'''

'\nfile_path=\'/home/jian/Projects/Big_Lots/Loyal_members/loyalty_register_data/New Reward Member Master as of 2018-07-03.txt\'\ndata_7=pd.read_csv(file_path,dtype=str,sep=\'|\',nrows=samplerows)\n\nprint(data_7.columns.tolist()==col_list)\nprint("data_7.shape",data_7.shape)\nprint("data_7[\'customer_id_hashed\'].nunique()",data_7[\'customer_id_hashed\'].nunique())\nprint("data_7[\'sign_up_date\'].min()",data_7[\'sign_up_date\'].min())\nprint("data_7[\'sign_up_date\'].max()",data_7[\'sign_up_date\'].max())\ndata_7[\'file_path\']=file_path\ndata_7.head(2)\n'

In [11]:
df_all_master=data_0.copy()
del data_0
gc.collect()
df_all_master=df_all_master.append(data_1)
del data_1
gc.collect()
df_all_master=df_all_master.append(data_2)
del data_2
gc.collect()
df_all_master=df_all_master.append(data_3)
del data_3
gc.collect()
df_all_master=df_all_master.append(data_4)
del data_4
gc.collect()
df_all_master=df_all_master.append(data_5)
del data_5
gc.collect()
df_all_master=df_all_master.append(data_6)
del data_6
gc.collect()

df_all_master=df_all_master.sort_values(['customer_id_hashed','sign_up_date'],ascending=[True,False]).drop_duplicates("customer_id_hashed")

In [12]:
list_weekly_master=list(recursive_file_gen("/home/jian/BigLots/"))
list_weekly_master=[x for x in list_weekly_master if "master" in x.lower() and x[-4:]==".txt"]
list_weekly_master.sort()
# list_weekly_master # looks good

In [13]:
list_weekly_master

['/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-06-30/New Reward Member Master as of 2018-07-03.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-07-14/MediaStormMasterBiWeekly20180717-132337-377.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-07-28/MediaStormMasterBiWeekly20180731-130714-098.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-08-11/MediaStormMasterBiWeekly20180814-130703-491.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-08-25/MediaStormMasterBiWeekly20180828-130708-295.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-09-08/MediaStormMasterBiWeekly20180911-132444-355.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-09-22/MediaStormMasterBiWeekly20180925-132449-459.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-10-06/MediaStormMasterBiWeekly20181009-132441-994.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-10-20/MediaStormMasterBiWeekly20181023-131639-747.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-11-03/MediaStormMasterBiWeekly20181106-131708-984.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-11-17/MediaStormMasterBiWeekly20181120-132340-144.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-12-01/MediaStormMasterBiWeekly20181204-130330-962.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-12-15/MediaStormMasterBiWeekly20181218-134118-875.txt',
 '/home/jian/BigLots/2018_by_weeks/MediaStorm_2018-12-29/MediaStormMasterBiWeekly20190101-132909-580.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-01-12/MediaStormMasterBiWeekly20190115-132855-055.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-01-26/MediaStormMasterBiWeekly20190129-130902-016.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-02-02/MediaStormMasterWeekly20190205-111610-675.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-02-09/MediaStormMasterWeekly20190212-122428-267.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-02-16/MediaStormMasterWeekly20190219-113650-867.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-02-23/MediaStormMasterWeekly20190226-112921-061.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-03-02/MediaStormMasterWeekly20190305-112945-302.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-03-09/MediaStormMasterWeekly20190312-121512-232.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-03-16/MediaStormMasterWeekly20190319-112932-415.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-03-23/MediaStormMasterWeekly20190326-113052-887.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-03-30/MediaStormMasterWeekly20190402-113131-172.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-04-06/MediaStormMasterWeekly20190409-124125-588.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-04-13/MediaStormMasterWeekly20190416-113034-995.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-04-20/MediaStormMasterWeekly20190423-112250-108.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-04-27/MediaStormMasterWeekly20190430-112348-844.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-05-04/MediaStormMasterWeekly20190507-112405-357.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-05-11/MediaStormMasterWeekly20190514-121253-492.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-05-18/MediaStormMasterWeekly20190521-111308-535.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-05-25/MediaStormMasterWeekly20190528-111239-184.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-06-01/MediaStormMasterWeekly20190604-112021-067.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-06-08/MediaStormMasterWeekly20190611-121921-488.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-06-15/MediaStormMasterWeekly20190618-112221-688.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-06-22/MediaStormMasterWeekly20190625-111845-768.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-06-29/MediaStormMasterWeekly20190702-113206-728.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-07-06/MediaStormMasterWeekly20190709-115819-602.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-07-13/MediaStormMasterWeekly20190716-123009-595.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-07-20/MediaStormMasterWeekly20190723-112911-431.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-07-27/MediaStormMasterWeekly20190730-113724-740.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-08-03/MediaStormMasterWeekly20190806-114102-298.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-08-10/MediaStormMasterWeekly20190813-120648-031.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-08-17/MediaStormMasterWeekly20190820-113748-487.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-08-24/MediaStormMasterWeekly20190827-113737-889.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-08-31/MediaStormMasterWeekly20190903-113802-440.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-09-07/MediaStormMasterWeekly20190910-120736-447.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-09-14/MediaStormMasterWeekly20190917-110653-239.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-09-21/MediaStormMasterWeekly20190924-112340-890.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-09-28/MediaStormMasterWeekly20191001-111526-231.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-10-05/MediaStormMasterWeekly20191008-121013-738.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-10-12/MediaStormMasterWeekly20191015-111356-088.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-10-19/MediaStormMasterWeekly20191022-111642-872.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-10-26/MediaStormMasterWeekly20191029-111418-126.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-11-02/MediaStormMasterWeekly20191105-111529-340.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-11-09/MediaStormMasterWeekly20191112-115559-074.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-11-16/MediaStormMasterWeekly20191119-112545-182.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-11-23/MediaStormMasterWeekly20191126-113236-194.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-11-30/MediaStormMasterWeekly20191203.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-12-07/MediaStormMasterWeekly20191211-170859-504.txt',
 '/home/jian/BigLots/2019_by_weeks/MediaStorm_2019-12-14/MediaStormMasterWeekly20191217-195802-250.txt',
 '/home/jian/BigLots/MediaStorm_2019-12-21/MediaStormMasterWeekly20191226-122746-283.txt',
 '/home/jian/BigLots/MediaStorm_2019-12-28/MediaStormMasterWeekly20191231-113542-859.txt']

In [15]:
list_weekly_master_df=[]
for file in list_weekly_master:
    df=pd.read_csv(file,dtype=str,nrows=samplerows,sep="|")
    print(os.path.basename(file),datetime.datetime.now(),df.columns.tolist()==col_list)
    df['file_path']=file
    list_weekly_master_df.append(df)
    
df_weekly_master=pd.concat(list_weekly_master_df)
del list_weekly_master_df

df_weekly_master=df_weekly_master.sort_values(['customer_id_hashed','sign_up_date'],ascending=[True,False]).drop_duplicates("customer_id_hashed")
gc.collect()

New Reward Member Master as of 2018-07-03.txt 2020-01-03 12:30:35.557756 True
MediaStormMasterBiWeekly20180717-132337-377.txt 2020-01-03 12:30:36.668379 True
MediaStormMasterBiWeekly20180731-130714-098.txt 2020-01-03 12:30:37.294679 True
MediaStormMasterBiWeekly20180814-130703-491.txt 2020-01-03 12:30:37.983489 True
MediaStormMasterBiWeekly20180828-130708-295.txt 2020-01-03 12:30:39.028817 True
MediaStormMasterBiWeekly20180911-132444-355.txt 2020-01-03 12:30:40.346072 True
MediaStormMasterBiWeekly20180925-132449-459.txt 2020-01-03 12:30:40.989209 True
MediaStormMasterBiWeekly20181009-132441-994.txt 2020-01-03 12:30:43.282143 True
MediaStormMasterBiWeekly20181023-131639-747.txt 2020-01-03 12:30:44.578168 True
MediaStormMasterBiWeekly20181106-131708-984.txt 2020-01-03 12:30:46.006695 True
MediaStormMasterBiWeekly20181120-132340-144.txt 2020-01-03 12:30:48.013130 True
MediaStormMasterBiWeekly20181204-130330-962.txt 2020-01-03 12:30:50.140304 True
MediaStormMasterBiWeekly20181218-134118-875.txt 2020-01-03 12:30:51.987873 True
MediaStormMasterBiWeekly20190101-132909-580.txt 2020-01-03 12:30:54.070604 True
MediaStormMasterBiWeekly20190115-132855-055.txt 2020-01-03 12:30:54.796182 True
MediaStormMasterBiWeekly20190129-130902-016.txt 2020-01-03 12:30:56.046981 True
MediaStormMasterWeekly20190205-111610-675.txt 2020-01-03 12:30:57.265021 True
MediaStormMasterWeekly20190212-122428-267.txt 2020-01-03 12:30:57.661870 True
MediaStormMasterWeekly20190219-113650-867.txt 2020-01-03 12:30:58.343355 True
MediaStormMasterWeekly20190226-112921-061.txt 2020-01-03 12:30:59.443946 True
MediaStormMasterWeekly20190305-112945-302.txt 2020-01-03 12:31:00.202518 True
MediaStormMasterWeekly20190312-121512-232.txt 2020-01-03 12:31:00.690285 True
MediaStormMasterWeekly20190319-112932-415.txt 2020-01-03 12:31:01.203472 True
MediaStormMasterWeekly20190326-113052-887.txt 2020-01-03 12:31:03.125689 True
MediaStormMasterWeekly20190402-113131-172.txt 2020-01-03 12:31:03.895990 True
MediaStormMasterWeekly20190409-124125-588.txt 2020-01-03 12:31:04.479504 True
MediaStormMasterWeekly20190416-113034-995.txt 2020-01-03 12:31:04.957597 True
MediaStormMasterWeekly20190423-112250-108.txt 2020-01-03 12:31:05.389405 True
MediaStormMasterWeekly20190430-112348-844.txt 2020-01-03 12:31:05.749109 True
MediaStormMasterWeekly20190507-112405-357.txt 2020-01-03 12:31:06.185803 True
MediaStormMasterWeekly20190514-121253-492.txt 2020-01-03 12:31:06.562613 True
MediaStormMasterWeekly20190521-111308-535.txt 2020-01-03 12:31:06.935341 True
MediaStormMasterWeekly20190528-111239-184.txt 2020-01-03 12:31:07.300849 True
MediaStormMasterWeekly20190604-112021-067.txt 2020-01-03 12:31:07.731489 True
MediaStormMasterWeekly20190611-121921-488.txt 2020-01-03 12:31:08.182039 True
MediaStormMasterWeekly20190618-112221-688.txt 2020-01-03 12:31:08.737685 True
MediaStormMasterWeekly20190625-111845-768.txt 2020-01-03 12:31:09.165012 True
MediaStormMasterWeekly20190702-113206-728.txt 2020-01-03 12:31:09.630815 True
MediaStormMasterWeekly20190709-115819-602.txt 2020-01-03 12:31:10.144371 True
MediaStormMasterWeekly20190716-123009-595.txt 2020-01-03 12:31:10.982581 True
MediaStormMasterWeekly20190723-112911-431.txt 2020-01-03 12:31:11.510038 True
MediaStormMasterWeekly20190730-113724-740.txt 2020-01-03 12:31:11.994832 True
MediaStormMasterWeekly20190806-114102-298.txt 2020-01-03 12:31:12.567087 True
MediaStormMasterWeekly20190813-120648-031.txt 2020-01-03 12:31:13.045618 True
MediaStormMasterWeekly20190820-113748-487.txt 2020-01-03 12:31:13.597832 True
MediaStormMasterWeekly20190827-113737-889.txt 2020-01-03 12:31:15.817187 True
MediaStormMasterWeekly20190903-113802-440.txt 2020-01-03 12:31:22.902538 True
MediaStormMasterWeekly20190910-120736-447.txt 2020-01-03 12:31:28.704514 True
MediaStormMasterWeekly20190917-110653-239.txt 2020-01-03 12:31:33.009520 True
MediaStormMasterWeekly20190924-112340-890.txt 2020-01-03 12:31:38.477027 True
MediaStormMasterWeekly20191001-111526-231.txt 2020-01-03 12:31:45.877376 True
MediaStormMasterWeekly20191008-121013-738.txt 2020-01-03 12:31:51.715734 True
MediaStormMasterWeekly20191015-111356-088.txt 2020-01-03 12:31:59.645467 True
MediaStormMasterWeekly20191022-111642-872.txt 2020-01-03 12:32:08.305037 True
MediaStormMasterWeekly20191029-111418-126.txt 2020-01-03 12:32:16.579250 True
MediaStormMasterWeekly20191105-111529-340.txt 2020-01-03 12:32:24.489889 True
MediaStormMasterWeekly20191112-115559-074.txt 2020-01-03 12:32:33.806861 True
MediaStormMasterWeekly20191119-112545-182.txt 2020-01-03 12:32:44.469779 True
MediaStormMasterWeekly20191126-113236-194.txt 2020-01-03 12:32:54.863085 True
MediaStormMasterWeekly20191203.txt 2020-01-03 12:33:06.428361 True
MediaStormMasterWeekly20191211-170859-504.txt 2020-01-03 12:33:17.770009 True
MediaStormMasterWeekly20191217-195802-250.txt 2020-01-03 12:33:30.669768 True
MediaStormMasterWeekly20191226-122746-283.txt 2020-01-03 12:33:54.621340 True
MediaStormMasterWeekly20191231-113542-859.txt 2020-01-03 12:34:17.967579 True

0

In [16]:
df_all_master=df_all_master.append(df_weekly_master)
del df_weekly_master
gc.collect()

df_all_master=df_all_master.sort_values(['customer_id_hashed','sign_up_date'],ascending=[True,False]).drop_duplicates("customer_id_hashed")
gc.collect()

0

In [17]:
print("df_all_master.shape",df_all_master.shape)
print("df_all_master['customer_id_hashed'].nunique()",df_all_master['customer_id_hashed'].nunique())
print("df_all_master['email_address_hash'].nunique()",df_all_master['email_address_hash'].nunique())

df_all_master.shape (32429970, 14)
df_all_master['customer_id_hashed'].nunique() 32429970
df_all_master['email_address_hash'].nunique() 32422418

In [18]:
df_all_master.head(2)

,customer_id_hashed,email_address_hash,sign_up_date,sign_up_channel,sign_up_location,customer_zip_code,transaction_count,transaction_amount,experian_multi_cluster,experian_demo_cluster,purchase_channel,email_unsubscribe_indicator,email_undeliverable_indicator,file_path
12625549,00000135f48c68690ad3d5fc9ada41bb5cd687452007e8...,4a1f9ca814426d0168b4ee9ac037be04151dff5631d78a...,2016-02-10,STORE,5309,36081,000000000000001.,0000000000000032.80,0,0,STORES,N,N,/home/jian/Projects/Big_Lots/Loyal_members/loy...
5068252,000001dadc0265bf9d250566d74e0006323f18b5826641...,26454de1f315ee0c13c8c9033f372f50a3f02a16691849...,2018-09-22,STORE,4061,93722,NaN,NaN,NaN,NaN,NaN,N,N,/home/jian/BigLots/New_Sing_Ups_2018_Fiscal_Ye...

In [19]:
# Clean dataframe column value types

df_all_master['sign_up_date']=pd.to_datetime(df_all_master['sign_up_date'],format="%Y-%m-%d").dt.date

#
df_all_master['sign_up_location']=df_all_master['sign_up_location'].fillna(-999).astype(int)
df_all_master['sign_up_location']=df_all_master['sign_up_location'].replace(-999,np.nan)

In [20]:
df_all_master['transaction_count']=df_all_master['transaction_count'].astype(float)
df_all_master['transaction_amount']=df_all_master['transaction_amount'].astype(float)
df_all_master['experian_multi_cluster']=df_all_master['experian_multi_cluster'].astype(float)
df_all_master['experian_demo_cluster']=df_all_master['experian_demo_cluster'].astype(float)

# 1. New Signs Up Table

In [21]:
# DB name: BigLots
BL_SQL_CONNECTION= 'mysql+pymysql://jian:JubaPlus-2017@localhost/BigLots'  # BL_Rewards_Master
BL_engine = create_engine(
        BL_SQL_CONNECTION, 
        pool_recycle=1800
    )

existing_tables=pd.read_sql("show tables;",con=BL_engine)
existing_tables

/usr/local/lib/python3.6/site-packages/pymysql/cursors.py:166: Warning: (1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")
  result = self._query(query)

   Tables_in_BigLots
0        BL_POS_Item
1    BL_POS_Subclass
2  BL_Rewards_Master

In [30]:
import pymysql.cursors
engine_pymysql_db_BL = pymysql.connect(host='localhost',user='jian',
                         password='JubaPlus-2017',db='BigLots',
                         charset='utf8mb4',cursorclass=pymysql.cursors.DictCursor)

In [31]:
def create_BL_Master_table():
    with engine_pymysql_db_BL.cursor() as cur:
        cur.execute("DROP TABLE IF EXISTS BL_Rewards_Master")
        cur.execute("CREATE TABLE BL_Rewards_Master \
        (\
        customer_id_hashed char(64), \
        email_address_hash char(64), \
        sign_up_date Date, \
        sign_up_channel varchar(64), \
        sign_up_location int, \
        customer_zip_code varchar(16), \
        transaction_count int, \
        transaction_amount decimal(10,2), \
        experian_multi_cluster varchar(32), \
        experian_demo_cluster varchar(32), \
        purchase_channel varchar(32), \
        email_unsubscribe_indicator varchar(2), \
        email_undeliverable_indicator varchar(2), \
        file_path varchar(256) \
        );")
    print("1:An empty TABLE BL_Rewards_Master has been created.",datetime.datetime.now())
 
 
create_BL_Master_table()

1:An empty TABLE BL_Rewards_Master has been created. 2020-01-03 13:04:45.171377

/usr/local/lib/python3.6/site-packages/pymysql/cursors.py:323: Warning: (1051, "Unknown table 'BigLots.BL_Rewards_Master'")
  self._do_get_result()

In [32]:
print(df_all_master.shape)
print(datetime.datetime.now(),"Start to sql")

(32429970, 14)
2020-01-03 13:04:47.502476 Start to sql

In [34]:
df_all_master.to_sql("BL_Rewards_Master",if_exists='replace', con=BL_engine, index=False,chunksize=300000,
                    dtype={
                        'customer_id_hashed':sqlalchemy.types.VARCHAR(length=64),
                        'email_address_hash':sqlalchemy.types.VARCHAR(length=64),
                        'sign_up_date':sqlalchemy.Date(), 
                        'sign_up_channel':sqlalchemy.types.VARCHAR(length=64),
                        'sign_up_location':sqlalchemy.types.INTEGER(),
                        'customer_zip_code':sqlalchemy.types.VARCHAR(length=16),
                        'transaction_count':sqlalchemy.types.INTEGER(),
                        'transaction_amount':sqlalchemy.types.DECIMAL(precision=10,scale=2,asdecimal=True),
                        'experian_multi_cluster':sqlalchemy.types.VARCHAR(length=32),
                        'experian_demo_cluster':sqlalchemy.types.VARCHAR(length=32),
                        'purchase_channel':sqlalchemy.types.VARCHAR(length=32),
                        'email_unsubscribe_indicator':sqlalchemy.types.VARCHAR(length=2),
                        'email_undeliverable_indicator':sqlalchemy.types.VARCHAR(length=2),
                        'file_path':sqlalchemy.types.VARCHAR(length=256)
                    })

In [35]:
print(datetime.datetime.now(),"Done to sql")

2020-01-03 14:07:50.473194 Done to sql

In [36]:
pd.read_sql("select count(customer_id_hashed) from BL_Rewards_Master;",con=BL_engine)

   count(customer_id_hashed)
0                   32429970

In [25]:
# Old
pd.read_sql("desc BL_Rewards_Master;",con=BL_engine)

                            Field           Type Null Key Default Extra
0              customer_id_hashed       char(64)  YES        None
1              email_address_hash       char(64)  YES        None
2                    sign_up_date           date  YES        None
3                 sign_up_channel    varchar(64)  YES        None
4                sign_up_location        int(11)  YES        None
5               customer_zip_code    varchar(16)  YES        None
6               transaction_count        int(11)  YES        None
7              transaction_amount  decimal(10,2)  YES        None
8          experian_multi_cluster    varchar(32)  YES        None
9           experian_demo_cluster    varchar(32)  YES        None
10               purchase_channel    varchar(32)  YES        None
11    email_unsubscribe_indicator     varchar(2)  YES        None
12  email_undeliverable_indicator     varchar(2)  YES        None

In [37]:
# New
pd.read_sql("desc BL_Rewards_Master;",con=BL_engine)

                            Field           Type Null Key Default Extra
0              customer_id_hashed    varchar(64)  YES        None
1              email_address_hash    varchar(64)  YES        None
2                    sign_up_date           date  YES        None
3                 sign_up_channel    varchar(64)  YES        None
4                sign_up_location        int(11)  YES        None
5               customer_zip_code    varchar(16)  YES        None
6               transaction_count        int(11)  YES        None
7              transaction_amount  decimal(10,2)  YES        None
8          experian_multi_cluster    varchar(32)  YES        None
9           experian_demo_cluster    varchar(32)  YES        None
10               purchase_channel    varchar(32)  YES        None
11    email_unsubscribe_indicator     varchar(2)  YES        None
12  email_undeliverable_indicator     varchar(2)  YES        None
13                      file_path   varchar(256)  YES        None

In [38]:
pd.read_sql("select max(sign_up_date) from BL_Rewards_Master;",con=BL_engine)

  max(sign_up_date)
0        2019-12-28