In [1]:
import pandas as pd
import csv
file_path="/home/jian/Projects/Smoothie_King/data/LoyaltyUser_102918.txt"

In [2]:
data=pd.read_table(file_path,sep=",",header=None)

/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2683: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
old_data_for_header=pd.read_table("/home/jian/Projects/Smoothie_King/data/LoyaltyUser.txt",nrows=1,sep=",",encoding="ISO-8859-1")
data.columns=old_data_for_header.columns

In [17]:
dup_email=data[data['email'].duplicated()]['email'].tolist()
df_dup_email=data[data['email'].isin(dup_email)]
df_dup_email=df_dup_email.sort_values(['email'])

In [23]:
df_dup_email

,version,start_date,end_date,tos,user_sk,user_id,user_name,first_name,last_name,email,...,zipcode,latitude,longitude,chain_id,joining_date,favorite_location,marketing_optin,marketing_optin_texting,Transaction_Count,Transaction_Amount
62698,2,2018-07-06,2199-12-31,NaN,18107727,4747659,NaN,Frashad,Harrell,046846031F5803F53B7616007E029DEC90429073941C33...,...,NaN,33.656354,-84.496427,63,2017-07-13,11906,N,NaN,61.0,40238.0
677299,1,1900-01-01,2017-05-09,NaN,5421932,2950403,NaN,Frashad,Harrell,046846031F5803F53B7616007E029DEC90429073941C33...,...,NaN,NaN,NaN,63,2014-04-05,0,Y,N,1.0,349.0
1333357,2,2018-10-07,2199-12-31,NaN,19243746,3651496,NaN,Gabrielle,Hazard,0B4347B0138C9962170F2080A48FF7A4D93D796C8C8870...,...,NaN,33.480524,-84.448495,63,2017-03-18,11932,N,NaN,1.0,1398.0
1210555,3,2018-09-25,2199-12-31,NaN,19108673,8613204,NaN,Gabrielle,Hazard,0B4347B0138C9962170F2080A48FF7A4D93D796C8C8870...,...,NaN,33.479292,-84.467531,63,2018-09-22,11932,N,NaN,NaN,NaN
1252305,1,1900-01-01,2017-05-15,NaN,6735453,4029795,NaN,Steven,Pino,0C239C32FB0FC56DDF8CF57CAB99A2CEE145BDB5106709...,...,34211.0,NaN,NaN,63,2013-07-29,0,Y,N,NaN,NaN
1123974,1,1900-01-01,2199-12-31,NaN,10973315,6205233,NaN,Steven,Pino,0C239C32FB0FC56DDF8CF57CAB99A2CEE145BDB5106709...,...,NaN,27.433697,-82.430327,63,2018-01-01,11942,N,NaN,4.0,2636.0
354050,2,2017-11-22,2199-12-31,NaN,9479124,3251199,NaN,Jordyn,Terrell,2232CE96F53A9AB44F9259EE57A71860A99D66A5A0F228...,...,NaN,33.866402,-84.626999,63,2017-02-07,11856,Y,NaN,45.0,39778.0
537057,1,1900-01-01,2199-12-31,NaN,5770908,3250976,NaN,Jordyn,Terrell,2232CE96F53A9AB44F9259EE57A71860A99D66A5A0F228...,...,30331.0,NaN,NaN,63,2016-12-21,0,Y,N,NaN,NaN
673674,4,2018-02-07,2199-12-31,NaN,11779018,3055844,NaN,NaN,NaN,2877E480BE39D63703CA0C3AFAE2020FD643C237FC64CB...,...,NaN,NaN,NaN,63,2015-05-15,11626,N,NaN,43.0,20035.0
1324377,1,1900-01-01,2017-01-20,NaN,5347994,2905410,NaN,NaN,NaN,2877E480BE39D63703CA0C3AFAE2020FD643C237FC64CB...,...,NaN,NaN,NaN,63,2015-05-15,0,N,N,NaN,NaN
599291,3,2018-02-07,2199-12-31,NaN,11781698,3048851,NaN,Allan,Domagas,2DCCF7FE1F7F9C090BE1F34C6C57A5B8017A2F181746E0...,...,34602.0,NaN,NaN,63,2015-03-17,11807,N,NaN,5.0,4033.0
165140,1,1900-01-01,2017-01-21,NaN,5365565,2887838,NaN,Allan,Domagas,2DCCF7FE1F7F9C090BE1F34C6C57A5B8017A2F181746E0...,...,34602.0,NaN,NaN,63,2015-03-17,11697,N,N,3.0,2043.0
197371,2,2017-01-25,2199-12-31,NaN,5550428,2975620,NaN,Antanya,Bentley,30B8F53E8342BEF37AA296911BDB478F4E8FD9F4EB9F73...,...,32218.0,NaN,NaN,63,2013-12-23,0,N,N,NaN,NaN
1327312,1,1900-01-01,2017-01-20,NaN,5344373,2909031,NaN,Antanya,Bentley,30B8F53E8342BEF37AA296911BDB478F4E8FD9F4EB9F73...,...,32218.0,NaN,NaN,63,2013-12-23,0,N,N,NaN,NaN
335149,2,2018-05-25,2199-12-31,NaN,17619735,7636726,NaN,mike,elijah,37366AB59E8EE5DACF898EDE19565903CDF28B191A7AD6...,...,NaN,0.000000,0.000000,63,2018-05-23,11980,N,NaN,1.0,599.0
1113989,1,1900-01-01,2199-12-31,NaN,14200527,7538386,NaN,elijah,ha,37366AB59E8EE5DACF898EDE19565903CDF28B191A7AD6...,...,NaN,40.789410,-73.723115,63,2018-05-11,11979,N,NaN,NaN,NaN
763323,2,2018-10-09,2199-12-31,NaN,19257796,6901902,NaN,tisha,zimmerman,4C1D1745AFD48D1A026F57594DD26D3C5D29ADE2A0C8B1...,...,NaN,32.739166,-97.064458,63,2018-03-03,13173,N,NaN,NaN,NaN
409374,1,1900-01-01,2199-12-31,NaN,17828472,7793942,NaN,tisha,zimmerman,4C1D1745AFD48D1A026F57594DD26D3C5D29ADE2A0C8B1...,...,NaN,32.593713,-96.937454,63,2018-06-12,13173,N,NaN,1.0,4690.0
958723,1,1900-01-01,2199-12-31,NaN,5392693,2927981,NaN,Andrew,Steib,4CE597E2992ECE8EF5C0F00A9A018ABEE36933E9967F5F...,...,70005.0,NaN,NaN,63,2016-09-19,0,N,N,NaN,NaN
49853,7,2018-08-26,2199-12-31,NaN,18711746,2927928,NaN,Andrew,Steib,4CE597E2992ECE8EF5C0F00A9A018ABEE36933E9967F5F...,...,70005.0,NaN,NaN,63,2016-09-19,12052,N,NaN,73.0,56267.0
809309,2,2018-09-10,2199-12-31,NaN,18924431,7460419,NaN,Lysandra,Hardaway,557D2A68310E9E6816DCC7869C6489C395DF95E3FBBE76...,...,NaN,33.681182,-84.227061,63,2018-05-02,11873,Y,NaN,34.0,23496.0
43661,3,2018-02-07,2199-12-31,NaN,11686484,3534439,NaN,Lysandra,Hardaway,557D2A68310E9E6816DCC7869C6489C395DF95E3FBBE76...,...,NaN,NaN,NaN,63,2014-05-17,11786,Y,NaN,90.0,56986.0
1305887,1,1900-01-01,2017-01-19,NaN,5340687,2912718,NaN,Dayna,Moore,5772B1B461304AB2DF72E681194ED72F7FB386509D748D...,...,28208.0,NaN,NaN,63,2013-11-30,11907,Y,N,NaN,NaN
312198,4,2018-02-07,2199-12-31,NaN,11779655,3054022,NaN,Dayna,Moore,5772B1B461304AB2DF72E681194ED72F7FB386509D748D...,...,28208.0,NaN,NaN,63,2013-11-30,11931,Y,NaN,26.0,17822.0
731871,1,1900-01-01,2199-12-31,NaN,18534991,8277642,NaN,james,allen,6837EBCB2192E3F9EC0B6C2043D527B6849361A48C59F9...,...,NaN,33.801053,-84.104325,63,2018-08-11,11857,Y,NaN,NaN,NaN
178074,2,2018-08-16,2199-12-31,NaN,18598504,7673839,NaN,James,Allen,6837EBCB2192E3F9EC0B6C2043D527B6849361A48C59F9...,...,30087.0,NaN,NaN,63,2013-10-02,0,Y,NaN,NaN,NaN
395470,1,1900-01-01,2199-12-31,NaN,10866915,6135718,NaN,bessie,callaham,6A6724AFD7F6E63705B20D7C2059278CA18909B55C72F2...,...,NaN,35.118597,-80.961994,63,2017-12-21,11913,Y,NaN,1.0,759.0
167690,3,2018-08-15,2199-12-31,NaN,18589304,4795436,NaN,Bessie,Callaham,6A6724AFD7F6E63705B20D7C2059278CA18909B55C72F2...,...,NaN,35.102777,-80.986182,63,2017-07-18,11913,N,NaN,10.0,8602.0
1235597,6,2018-07-09,2199-12-31,NaN,18143632,3423572,NaN,lisa,roberts,6FC590707F9EBD89D4017C96A41705EA5E672D83751CA6...,...,75169.0,NaN,NaN,63,2013-05-11,11714,Y,NaN,2.0,9146.0
1173805,1,1900-01-01,2199-12-31,NaN,11026152,6258486,NaN,Lisa,Roberts,6FC590707F9EBD89D4017C96A41705EA5E672D83751CA6...,...,NaN,0.000000,0.000000,63,2018-01-05,11714,Y,NaN,3.0,7086.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240968,1,1900-01-01,2199-12-31,NaN,9008809,5638194,NaN,gwen,bedas,9BBF86D412231ED905072F51EA37AF3ADAD1D5281B2235...,...,NaN,10.396164,123.986836,63,2017-10-15,11751,Y,N,NaN,NaN
757533,1,1900-01-01,2017-09-22,NaN,6324796,3691851,NaN,gwen,bedas,9BBF86D412231ED905072F51EA37AF3ADAD1D5281B2235...,...,NaN,10.396124,123.986834,63,2017-03-22,11751,Y,N,NaN,NaN
1159207,2,2018-09-15,2199-12-31,NaN,18987490,5088135,NaN,Autumn,Wells,A4F592694FBDB3D3531DD7A0A54FF7118876F94DC58BDF...,...,NaN,30.418278,-91.051289,63,2017-08-17,11639,Y,NaN,13.0,13090.0
251309,2,2018-09-13,2199-12-31,NaN,18960181,7997514,NaN,Autumn,Wells,A4F592694FBDB3D3531DD7A0A54FF7118876F94DC58BDF...,...,NaN,30.351515,-91.065424,63,2018-07-08,12094,Y,NaN,NaN,NaN
1331025,1,1900-01-01,2017-09-11,NaN,7633339,4720488,NaN,Eric,Beasley,AC4CA50DEF9EDC3ECD1FC83187E0BAB04A473020FCF5E0...,...,NaN,30.656148,-88.177805,63,2017-07-10,11628,Y,N,NaN,NaN
997586,4,2018-10-28,2199-12-31,NaN,19394130,3842806,NaN,Eric,Beasley,AC4CA50DEF9EDC3ECD1FC83187E0BAB04A473020FCF5E0...,...,NaN,30.672287,-88.147644,63,2017-04-05,11628,Y,NaN,8.0,5264.0
93428,3,2017-07-04,2199-12-31,NaN,7561842,4372866,NaN,angel,boyd,B379A8D1D2E6511BAF38A5A391F77B703610D7527E3EB7...,...,NaN,34.090584,-81.172884,63,2017-06-01,12390,Y,Y,21.0,11640.0
39382,1,1900-01-01,2017-06-26,NaN,7453620,4575664,NaN,angel,boyd,B379A8D1D2E6511BAF38A5A391F77B703610D7527E3EB7...,...,NaN,34.176548,-81.397343,63,2017-06-23,12390,Y,Y,1.0,499.0
1028591,11,2017-11-29,2199-12-31,NaN,9541873,3362543,NaN,imani,mccreary,B5563A3840274A13FAB1D9D6113718C574CD428169242F...,...,NaN,37.802693,-121.973037,63,2017-02-17,11979,Y,NaN,1.0,769.0
165397,2,2017-02-01,2017-02-16,NaN,5669469,2897907,NaN,Imani,Mccreary,B5563A3840274A13FAB1D9D6113718C574CD428169242F...,...,11238.0,NaN,NaN,63,2016-11-29,0,N,N,NaN,NaN
264984,6,2018-02-07,2199-12-31,NaN,11733132,3240825,NaN,Sherie,Rowe-Haynes,B5C7C425057C17F7884FD2BC3F0C1BB23C9F9698854ACA...,...,63120.0,NaN,NaN,63,2014-06-05,12122,Y,NaN,8.0,5233.0
894225,1,1900-01-01,2017-08-13,NaN,8029168,5030913,NaN,sherie,RH,B5C7C425057C17F7884FD2BC3F0C1BB23C9F9698854ACA...,...,NaN,17.957305,-76.912355,63,2017-08-11,12050,N,N,NaN,NaN
754873,3,2018-09-17,2199-12-31,NaN,19013657,4035126,NaN,Douglas,Pena,B76850C8DF92F6B9D8C9C31C34CC9D28EF9EA5DDCE4EC9...,...,NaN,25.777154,-80.188466,63,2017-04-25,12113,N,NaN,1.0,489.0
1040667,1,1900-01-01,2199-12-31,NaN,18980807,8547458,NaN,Douglas,Pena,B76850C8DF92F6B9D8C9C31C34CC9D28EF9EA5DDCE4EC9...,...,NaN,25.795487,-80.128392,63,2018-09-14,12113,N,NaN,NaN,NaN
351894,1,1900-01-01,2199-12-31,NaN,8786410,5490028,NaN,Sharon,Percell,BEBC3D12C3EF5EBCFB3BBDB2EB2BB6AF528CC514CEBF52...,...,NaN,30.458704,-91.212964,63,2017-09-30,11909,Y,Y,NaN,NaN
1060381,3,2017-12-28,2199-12-31,NaN,10915030,5226964,NaN,Sharon,Percell,BEBC3D12C3EF5EBCFB3BBDB2EB2BB6AF528CC514CEBF52...,...,70767.0,NaN,NaN,63,2013-02-24,0,Y,NaN,NaN,NaN
785059,1,1900-01-01,2199-12-31,NaN,8014032,5023426,NaN,jordan,sternblitz,C5E0F55B2F54109432A7D1F365647E5B8C0DFD0AAC53B3...,...,NaN,32.909613,-96.802385,63,2017-08-10,11645,N,N,NaN,NaN
1246819,2,2018-08-18,2199-12-31,NaN,18623756,3539698,NaN,Jordan,Sternblitz,C5E0F55B2F54109432A7D1F365647E5B8C0DFD0AAC53B3...,...,NaN,32.938607,-96.839508,63,2017-03-07,11645,N,NaN,6.0,5168.0
1219365,1,1900-01-01,2017-08-28,NaN,8229886,5178651,NaN,Temarrio,thomas,D13ADD863E292044DE01A22C6B75DBFC2A975030E55B7F...,...,NaN,33.654812,-84.501553,63,2017-08-26,11933,N,Y,NaN,0.0
95198,5,2018-02-07,2199-12-31,NaN,11608648,5178621,NaN,Temarrio,Thomas,D13ADD863E292044DE01A22C6B75DBFC2A975030E55B7F...,...,30313.0,NaN,NaN,63,2013-03-27,11778,N,NaN,20.0,17989.0
937555,5,2018-02-20,2199-12-31,NaN,12148582,3605241,NaN,Teajuanna,Hudson,D736335E140437A57FC8627E7EBF496A2B2BD8E61D04F5...,...,30238.0,NaN,NaN,63,2016-04-04,12394,Y,NaN,27.0,20452.0
300423,1,1900-01-01,2017-10-05,NaN,6216960,3604687,NaN,Teajuanna,Hudson,D736335E140437A57FC8627E7EBF496A2B2BD8E61D04F5...,...,NaN,33.532310,-84.362132,63,2017-03-14,12394,Y,N,NaN,NaN
1210089,1,1900-01-01,2199-12-31,NaN,9041907,5654962,NaN,Erv,Lanier,DB3BED44A432C0849E6054C012DB65D1B1C3D46E75AC38...,...,NaN,NaN,NaN,63,2013-11-01,0,Y,N,NaN,NaN
832553,4,2017-10-24,2199-12-31,NaN,9132149,4732620,NaN,erv,lanier,DB3BED44A432C0849E6054C012DB65D1B1C3D46E75AC38...,...,NaN,0.000000,0.000000,63,2017-07-11,12188,N,NaN,5.0,2854.0
677284,1,1900-01-01,2017-01-20,NaN,5351506,2901898,NaN,Chad,NaN,DE7C8F9B258EEC9AA3500776434B7B049D071CBE1E02E2...,...,70123.0,NaN,NaN,63,2012-07-26,0,Y,N,1.0,779.0
375762,2,2017-01-26,2199-12-31,NaN,5567847,3000812,NaN,Chad,NaN,DE7C8F9B258EEC9AA3500776434B7B049D071CBE1E02E2...,...,70123.0,NaN,NaN,63,2012-07-26,0,Y,N,NaN,0.0
1142467,4,2018-02-02,2199-12-31,NaN,11482525,2992787,NaN,McKenzey,Geers,DFE3F080A9C4796B18170EF45982084A4D58322A97FD0D...,...,46514.0,NaN,NaN,63,2016-12-14,12263,Y,NaN,77.0,55258.0
397553,1,1900-01-01,2017-01-20,NaN,5364135,2889268,NaN,McKenzey,Geers,DFE3F080A9C4796B18170EF45982084A4D58322A97FD0D...,...,46514.0,NaN,NaN,63,2016-12-14,0,Y,N,NaN,NaN
995198,1,1900-01-01,2017-01-19,NaN,5320239,2884357,NaN,Andy,Williams,EA5A6CB8A0E8A141BACF96A5573C68E06E51E84E8A7E63...,...,74136.0,NaN,NaN,63,2013-08-22,0,N,N,NaN,NaN
151420,13,2018-08-16,2199-12-31,NaN,18600441,2978048,NaN,Andy,Williams,EA5A6CB8A0E8A141BACF96A5573C68E06E51E84E8A7E63...,...,74136.0,NaN,NaN,63,2013-08-22,11816,N,NaN,60.0,48376.0

In [14]:
data[['email']].drop_duplicates().to_csv("/home/jian/Projects/Smoothie_King/data/SK_LoyaltyUser_Unique_id_JL_20181029.csv",index=False)

In [6]:
len(data['email'].unique())

1339672

In [7]:
len(data['user_id'].unique())

1339707

In [15]:
data[['email']].drop_duplicates().shape

(1339672, 1)

In [24]:
data.to_csv("/home/jian/Projects/Smoothie_King/data/SK_LoyaltyUser_JL_20181029.csv",index=False)