In [1]:
from google.cloud import bigquery

In [2]:
client = bigquery.Client()

In [3]:
query="select * from mdb.vw__installer_master limit 200"

In [5]:
query_job = client.query(query)  # Make an API request.

In [6]:
query_job

In [7]:
df=query_job.result().to_dataframe()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: PyarrowMissingWarning: Converting to a dataframe without pyarrow installed is often slower and will become unsupported in the future. Please install the pyarrow package.
  """Entry point for launching an IPython kernel.

In [9]:
df

,company_owned_store_ind,open_date,close_date,installer_store_num,installer_name,address_1,city,state,zip_cd,country,owner_num,head_office_num,owner_name,store_num,file_id,record_id,create_process_log_id,update_process_log_id
0,N,2015-08-25,NaT,0000162876,POMPS TIRE SERVICE,21840 INDUSTRIAL COURT,ROGERS,MN,55374,US,8416,0002003298,POMPS TIRE SERVICE INC,2876,25749,318000003,1956,158892
1,N,2018-01-19,NaT,0000143309,PETES AUTO CARE INC,2501 EAST 29TH STREET,BRYAN,TX,77802,US,None,0000143309,PETES AUTO CARE INC,3309,25479,409000004,1956,157190
2,N,2015-05-13,NaT,0000149121,POWERS TIRE AND AUTO,2 MADISON,FORT ATKINSON,WI,53538,US,None,0000149121,G5 SERVICES INC,9121,25344,684000009,1956,156294
3,N,2017-01-05,NaT,0000138751,BEST TIRE AND AUTO LLC,1646 S COLLEGE STREET,AUBURN,AL,36832,US,None,0000138751,BEST TIRE AND AUTO LLC,8751,7241,868000001,1956,34902
4,N,2017-01-03,NaT,0000165923,A-ONE TIRE SALES,4847 US 84 EAST,DOTHAN,AL,36301,US,None,0000165923,MCKENZIE INC DBA A-ONE TIRE,5923,10970,418000001,1956,61818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,N,2016-07-25,2019-01-31,0000138130,MCKINNEY TIRE & APPLIANCE,1030 N MCDONALD ST,MCKINNEY,TX,75069,US,None,0000138130,MEEKS MTA LLC,8130,6900,284000003,1956,32454
196,N,2017-05-01,NaT,0000139247,TOMBALL COMPLETE AUTO CARE,27503 TOMBALL PARKWAY,TOMBALL,TX,77375,US,3191,0000139247,TOMBALL AUTO & TIRES,9247,12169,698000003,1956,70414
197,N,2017-08-07,NaT,0000176124,"RED RIVER TIRE CENTERS, INC",702 N MAIN ST,BONHAM,TX,75418-3796,US,5878,0000176123,RED RIVER TIRE CENTER,6124,9204,136000003,1956,49059
198,N,2018-02-20,2019-09-03,0000181731,SUPERIOR TIRE & SERVICE,2307 NEDERLAND AVE,NEDERLAND,TX,77627,US,6142,0000176476,ORANGE SUPERIOR TIRE INC,1731,13551,435000003,1956,80655
199,N,2018-02-20,NaT,0000169338,ORANGE SUPERIOR TIRE INC,1001 S 11TH ST,BEAUMONT,TX,77701,US,6142,0000176476,ORANGE SUPERIOR TIRE INC,9338,5840,102000002,1956,24759