In [1]:
import pandas as pd
import json
import datetime
import os
import numpy as np
from haversine import haversine
os.getcwd()

'/home/jian/Projects/Big_Lots/Analysis/2019_Q3/Planner_request/Margaret_zips_for_LayborDay_20190821'

In [2]:
zip_centers=json.load(open("/home/jian/Docs/Geo_mapping/updated_zip_centers_JL_2019-05-23.json","r"))

In [3]:
df_stores_wanted=pd.read_excel("./2019 Labor Day SOTF Marketing - Stores 8.20.19.xlsx",sheet_name="Sheet1",skiprows=3,dtype=str)
list_stores_wanted=df_stores_wanted["Store#"].unique().tolist()

del df_stores_wanted['Unnamed: 0']
del df_stores_wanted['Unnamed: 1']
del df_stores_wanted['Unnamed: 2']

In [4]:
excel_file_new_Ta=pd.ExcelFile("/home/jian/Projects/Big_Lots/New_TA/TA_created_in_201906/final_output_20190718/BL_final_TA_updated_remove_8_closing_stores_JL_2019-08-20.xlsx")
excel_file_new_Ta.sheet_names

['unique_zips_full_footprint', 'view_by_TA', 'view_by_store']

In [5]:
df_store_list=pd.read_table("/home/jian/BigLots/static_files/Store_list/MediaStormStores20190801-135940-752.txt",sep="|",dtype=str)
df_store_list.head(2)

,location_id,location_desc,open_dt,close_dt,address_line_1,address_line_2,city_nm,state_nm,zip_cd,longitude_meas,latitude_meas,sales_square_feet,furniture_sales_square_feet
0,1,BERWICK SHOPPING CENTER,1983-09-15,NaN,2837 WINCHESTER PIKE,NaN,COLUMBUS,OH,43232-9301,-000000000082.914789,000000000039.913636,00000000029217.0000,00000000006692.0000
1,29,ATHENS SHOPPING CENTER,1984-03-26,NaN,918 E STATE ST,NaN,ATHENS,OH,45701-2188,-000000000082.069765,000000000039.337172,00000000026545.0000,00000000005694.0000

In [6]:
df_store_list=pd.read_table("/home/jian/BigLots/static_files/Store_list/MediaStormStores20190801-135940-752.txt",sep="|",dtype=str)
df_output=df_store_list[['location_id','latitude_meas','longitude_meas']]
df_output['latitude_meas']=df_output['latitude_meas'].astype(float)
df_output['longitude_meas']=df_output['longitude_meas'].astype(float)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [7]:
df_zips_by_store=excel_file_new_Ta.parse("view_by_store",dtype=str)
df_iter=df_zips_by_store[df_zips_by_store['location_id'].isin(list_stores_wanted)]

df_mapping_store_zips=pd.DataFrame(columns=["location_id","zip_cd","trans_flag"])

for ind, row in df_iter.iterrows():
    store_number=row['location_id']
    P_zips=eval(row['all_trans_P_zips'])
    df_P=pd.DataFrame({"zip_cd":P_zips},index=["P"]*len(P_zips)).reset_index().rename(columns={"index":"trans_flag"})
    
    S_zips=eval(row['all_trans_S_zips'])
    df_S=pd.DataFrame({"zip_cd":S_zips},index=["S"]*len(S_zips)).reset_index().rename(columns={"index":"trans_flag"})
    
    dist_10_zips=eval(row['zips_in_10'])
    df_10_miles=pd.DataFrame({"zip_cd":dist_10_zips},index=["zips_in_10"]*len(dist_10_zips)).reset_index().rename(columns={"index":"trans_flag"})
    
    df=pd.concat([df_P,df_S,df_10_miles])
    df['location_id']=store_number
    df_mapping_store_zips=df_mapping_store_zips.append(df)

In [8]:
df_output=pd.merge(df_mapping_store_zips,df_output,on="location_id",how="left")
df_output.shape

(434, 5)

In [9]:
def get_dist_miles(zip_cd_str,lat,long):
    try:
        return haversine([lat,long],zip_centers[zip_cd_str],miles=True)
    except:
        return np.nan
    
df_output['dist_miles']=df_output.apply(lambda x: get_dist_miles(x['zip_cd'],x['latitude_meas'],x['longitude_meas']),axis=1)
df_output=df_output.rename(columns={"location_id":"Store#"})
df_output=df_output[((df_output['trans_flag']=="P") | (df_output['dist_miles']<=20))]

In [10]:
df_output=pd.merge(df_stores_wanted,df_output,on="Store#",how="left")

In [11]:
df_output_unique=df_output[['zip_cd','trans_flag']].sort_values(['zip_cd','trans_flag'])

df_output_unique=df_output_unique.drop_duplicates("zip_cd").sort_values(["trans_flag",'zip_cd'])

In [12]:
writer=pd.ExcelWriter("./BL_zips_for_2019LayborDay_SOTF_JL_"+str(datetime.datetime.now().date())+".xlsx",engine="xlsxwriter")
df_output_unique.to_excel(writer,"unique_zip_cd",index=False)
df_output.to_excel(writer,"zip_by_store",index=False)
writer.save()

In [13]:
df_store_list[df_store_list['location_id'].isin(list_stores_wanted)]

,location_id,location_desc,open_dt,close_dt,address_line_1,address_line_2,city_nm,state_nm,zip_cd,longitude_meas,latitude_meas,sales_square_feet,furniture_sales_square_feet
54,391,D & L PLZ,1990-11-12,NaN,5165 BROADWAY,NaN,DEPEW,NY,14043-4012,-000000000078.683772,000000000042.901356,00000000018352.0000,00000000002654.0000
116,1018,NaN,1995-11-04,NaN,21 S MAIN ST,NaN,JAMESTOWN,NY,14701-6634,-000000000079.236407,000000000042.093175,00000000023403.0000,00000000004836.0000
259,831,NaN,1994-04-28,NaN,5987 S TRANSIT RD,NaN,LOCKPORT,NY,14094-6305,-000000000078.694654,000000000043.137017,00000000022103.0000,00000000003406.0000
304,1178,COLUMBIA NORTHEAST SHOPPING CENTER,1997-10-12,NaN,9221 TWO NOTCH RD STE 30,NaN,COLUMBIA,SC,29223-6428,-000000000080.923807,000000000034.096512,00000000016031.0000,00000000002109.0000
426,1692,WESMARK PLAZA,2002-07-11,NaN,1121 BROAD ST,NaN,SUMTER,SC,29150-1902,-000000000080.374460,000000000033.954456,00000000021874.0000,00000000003060.0000
511,1404,D&F PLZ,1998-11-22,NaN,1170 CENTRAL AVE,NaN,DUNKIRK,NY,14048-3424,-000000000079.328080,000000000042.458276,00000000023574.0000,00000000004867.0000
536,1520,NaN,2000-07-13,NaN,1980 RIDGE RD,NaN,WEST SENECA,NY,14224-3312,-000000000078.778207,000000000042.830778,00000000022480.0000,00000000004514.0000
561,1629,YOUNGMANN PLAZA,2001-10-12,NaN,750 YOUNG ST,NaN,TONAWANDA,NY,14150-4101,-000000000078.858223,000000000043.001400,00000000026512.0000,00000000005922.0000
603,1762,SOUTH OGDEN SHOPPING CENTER,2003-07-18,NaN,698 S OGDEN ST,NaN,BUFFALO,NY,14206-2317,-000000000078.802542,000000000042.881185,00000000023361.0000,00000000003781.0000
635,1851,DELAWARE PARK CENTRE,2004-08-13,NaN,502 N UNION ST,NaN,OLEAN,NY,14760-2619,-000000000078.428947,000000000042.085270,00000000020350.0000,00000000003675.0000
637,1857,WOODBERRY PLAZA,2004-09-09,NaN,3230 AUGUSTA RD,NaN,WEST COLUMBIA,SC,29170-2833,-000000000081.127249,000000000033.978162,00000000026226.0000,00000000005924.0000
655,1914,CENTRAL PARK SHOPPING CENTER,2002-10-12,NaN,7475 E ILIFF AVE,NaN,DENVER,CO,80231-5368,-000000000104.902174,000000000039.675627,00000000024289.0000,00000000003667.0000
658,1920,ENGLEWOOD MARKET PLACE,2003-05-02,NaN,139 W HAMPDEN AVE,NaN,ENGLEWOOD,CO,80110-2408,-000000000104.989394,000000000039.654336,00000000026102.0000,00000000003855.0000
681,1991,FOOD LION PLZ,2005-11-10,NaN,1371 CHESTNUT ST,NaN,ORANGEBURG,SC,29115-3452,-000000000080.862133,000000000033.513310,00000000023759.0000,00000000003975.0000
709,4117,CUB SQUARE S/C,1986-12-17,NaN,8125 SHERIDAN BLVD,NaN,ARVADA,CO,80003-1911,-000000000105.054966,000000000039.844612,00000000021680.0000,00000000003839.0000
782,1839,HAMBURG PLAZA,2004-07-22,NaN,5999 S PARK AVE,NaN,HAMBURG,NY,14075-3719,-000000000078.827060,000000000042.733097,00000000021398.0000,00000000003727.0000
788,1852,JO ANN SUPERSTORE PLZ,2004-09-03,NaN,4101 TRANSIT RD,NaN,BUFFALO,NY,14221-7243,-000000000078.695225,000000000042.958595,00000000019196.0000,00000000003340.0000
796,1874,RIVER OAKS PLAZA,2004-10-28,NaN,2209 W DEKALB ST,NaN,CAMDEN,SC,29020-2158,-000000000080.647212,000000000034.247842,00000000021627.0000,00000000003152.0000
863,4121,FOSSIL CREEK PLZ,1987-03-28,NaN,126 W TROUTMAN PKWY,NaN,FORT COLLINS,CO,80525-3037,-000000000105.078815,000000000040.529351,00000000023750.0000,00000000004097.0000
868,4133,NaN,1987-09-30,NaN,15351 E HAMPDEN AVE,NaN,AURORA,CO,80013-2401,-000000000104.809194,000000000039.654645,00000000024059.0000,00000000004344.0000
910,4341,JEWELL SQUARE S/C,1995-01-09,NaN,7777 W JEWELL AVE,NaN,LAKEWOOD,CO,80232-6843,-000000000105.084670,000000000039.683856,00000000019923.0000,00000000005000.0000
935,4490,UNIVERSITY SQUARE,2004-08-15,NaN,2628 11TH AVE,NaN,GREELEY,CO,80631-8441,-000000000104.694291,000000000040.394603,00000000022878.0000,00000000004580.0000
941,4513,PLAZA ON THE GREEN,2005-09-15,NaN,8100 W CRESTLINE AVE UNIT B5,NaN,LITTLETON,CO,80123-1270,-000000000105.088679,000000000039.616577,00000000025035.0000,00000000004430.0000
943,4517,TIME SQUARE SHOPPING CENTER,2006-02-24,NaN,4260 WADSWORTH BLVD,NaN,WHEAT RIDGE,CO,80033-4620,-000000000105.080145,000000000039.773805,00000000025050.0000,00000000004880.0000
965,4572,ALBERTSONS,2011-08-25,NaN,893 S KUNER RD.,NaN,BRIGHTON,CO,80601-2857,-000000000104.829103,000000000039.973090,00000000020736.0000,00000000002824.0000
970,4586,ARAPAHOE CROSSINGS,2011-08-11,NaN,6626 SOUTH PARKER ROAD,NaN,AURORA,CO,80016-1084,-000000000104.802604,000000000039.595802,00000000021353.0000,00000000002390.0000
1040,5123,SEVEN OAKS SHOPPING CENTER,2010-09-29,NaN,6169 ST. ANDREWS RD.,NaN,COLUMBIA,SC,29212-3146,-000000000081.161318,000000000034.056450,00000000021089.0000,00000000002934.0000
1086,4486,SHERIDAN CROSSING,2004-07-09,NaN,4830 W 120TH AVE,NaN,WESTMINSTER,CO,80020-3329,-000000000105.048677,000000000039.912204,00000000026455.0000,00000000004598.0000
1227,5204,YORKSHIRE PLAZA,2011-11-08,NaN,12177 ROUTE 16,NaN,CHAFFEE,NY,14030-9602,-000000000078.489806,000000000042.522220,00000000024498.0000,00000000005549.0000
1296,5353,BRADFORD MALL,2017-09-28,NaN,1001 E MAIN ST,NaN,BRADFORD,PA,16701-3215,-000000000078.619652,000000000041.980983,00000000030310.0000,00000000006029.0000