In [1]:
import pandas as pd
import os
import datetime
import numpy as np

In [2]:
os.getcwd()

'/home/jian/Projects/Big_Lots/Analysis/2019_Q1/Planner_Request/Store_counts_SOTF_ocunts_by_Q4_Quadrants_Bruce_20190418'

In [3]:
SOTF_list=pd.ExcelFile("/home/jian/Projects/Big_Lots/Analysis/2019_Q1/Planner_Request/Store_counts_SOTF_ocunts_by_Q4_Quadrants_Bruce_20190418/Store List Report 04.05.19 330PM.xlsx")
print(SOTF_list.sheet_names)
SOTF_list=SOTF_list.parse("Store List",dtype=str)
SOTF_list=SOTF_list.iloc[:1408,:]

['Store List', 'Sheet7', 'Sheet6', 'Sheet5', 'Distribution', 'Sheet1', 'Sheet3', 'Sheet4']

In [4]:
print(SOTF_list['SOTF'].unique().tolist())
SOTF_list=SOTF_list[SOTF_list['SOTF']=="Yes"]
SOTF_list['Open Date']=SOTF_list['Open Date'].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d %H:%M:%S").date())
SOTF_list_before_Nov_1_2018=SOTF_list[SOTF_list['Open Date']<datetime.date(2018,11,1)]
SOTF_list_before_Nov_1_2018=SOTF_list_before_Nov_1_2018[['Store','SOTF']].rename(columns={"Store":"location_id"})

['Yes', 'nan', '2019', 'No']

In [5]:
Q4_quadrant_definations=pd.read_excel("/home/jian/Projects/Big_Lots/Analysis/2019_Q1/Planner_Request/Store_counts_SOTF_ocunts_by_Q4_Quadrants_Bruce_20190418/Excel_BL_2018_Q4_post_YoY_small_JL_2019-03-04.xlsx",
                                      sheetname="Q4_Store_Quadrant_Defination",dtype=str,usecols=["location_id",'Quadrant'])
Q4_quadrant_definations.shape

(1361, 2)

In [6]:
Q4_quadrant_definations=pd.merge(Q4_quadrant_definations,SOTF_list_before_Nov_1_2018,on="location_id",how="outer")
Q4_quadrant_definations['Quadrant']=Q4_quadrant_definations['Quadrant'].fillna("NotDefined")
Q4_quadrant_definations['SOTF']=Q4_quadrant_definations['SOTF'].fillna("No")
summary=Q4_quadrant_definations.groupby(['Quadrant','SOTF'])['location_id'].count().to_frame().reset_index()

In [8]:
writer=pd.ExcelWriter("/home/jian/Projects/Big_Lots/Analysis/2019_Q1/Planner_Request/Store_counts_SOTF_ocunts_by_Q4_Quadrants_Bruce_20190418/BL_summary_SOTF_count_before_2018Nov_JL_20180418.xlsx",engine="xlsxwriter")
Q4_quadrant_definations.to_excel(writer,"Store_Quadrant_with_SOTF",index=False)
summary.to_excel(writer,"summary_1",index=False)
writer.save()

In [7]:
Q4_quadrant_definations

     location_id      Quadrant SOTF
0              1    Quadrant I  Yes
1              3    Quadrant I   No
2             29   Quadrant IV   No
3             30   Quadrant IV   No
4             32    Quadrant I   No
5             42    Quadrant I   No
6             43   Quadrant IV   No
7             45    Quadrant I   No
8             49    Quadrant I  Yes
9             51    Quadrant I   No
10            58    Quadrant I   No
11            62   Quadrant IV   No
12            64    Quadrant I   No
13            72   Quadrant II   No
14            77    Quadrant I   No
15            82    Quadrant I   No
16            83   Quadrant IV  Yes
17            86    Quadrant I   No
18            91  Quadrant III   No
19            98   Quadrant IV   No
20           109    Quadrant I   No
21           111   Quadrant IV   No
22           122   Quadrant IV   No
23           132  Quadrant III   No
24           134    Quadrant I   No
25           135    Quadrant I   No
26           137    Quadrant I   No
27           138   Quadrant IV   No
28           152    Quadrant I   No
29           153    Quadrant I   No
...          ...           ...  ...
1354        5354   Quadrant II  Yes
1355        5355   Quadrant II   No
1356        5356   Quadrant II  Yes
1357        5357   Quadrant II   No
1358        5358  Quadrant III  Yes
1359        5359   Quadrant II  Yes
1360        5360  Quadrant III  Yes
1361         117    NotDefined  Yes
1362         219    NotDefined  Yes
1363        1006    NotDefined  Yes
1364        1260    NotDefined  Yes
1365        1964    NotDefined  Yes
1366        4675    NotDefined  Yes
1367        4676    NotDefined  Yes
1368        4677    NotDefined  Yes
1369        4680    NotDefined  Yes
1370        4681    NotDefined  Yes
1371        5362    NotDefined  Yes
1372        5363    NotDefined  Yes
1373        5364    NotDefined  Yes
1374        5365    NotDefined  Yes
1375        5366    NotDefined  Yes
1376        5367    NotDefined  Yes
1377        5368    NotDefined  Yes
1378        5369    NotDefined  Yes
1379        5371    NotDefined  Yes
1380        5374    NotDefined  Yes
1381        5376    NotDefined  Yes
1382        5377    NotDefined  Yes
1383        1918    NotDefined  Yes

[1384 rows x 3 columns]